// =============================================================
// WEARABLE TECH HUB — Comprehensive Product Database
// All products sourced from amazon.ca with affiliate links
// Affiliate Tag: weyoowte-20
// =============================================================

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviewCount: number;
  badge?: "editors-choice" | "best-value" | "new" | "top-rated";
  image: string;
  amazonUrl: string;
  shortDescription: string;
  pros: string[];
  cons: string[];
  specs: Record<string, string>;
  score: {
    design: number;
    performance: number;
    battery: number;
    value: number;
    features: number;
  };
  featured?: boolean;
}

export interface Category {
  id: string;
  name: string;
  description: string;
  image: string;
  productCount: number;
}

export const AFFILIATE_TAG = "weyoowte-20";

export const categories: Category[] = [
  {
    id: "smartwatches",
    name: "Smartwatches & Accessories",
    description: "Full-featured wrist computers with health monitoring, GPS, and smart notifications",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663651644589/cNZFBcai4VvVZ9Us6eXbuZ/smartwatch-category-WKqFe94BYAPt8V4kiLX3gD.webp",
    productCount: 5,
  },
  {
    id: "fitness-trackers",
    name: "Sport Activity Trackers",
    description: "Lightweight bands focused on activity, sleep, and heart rate tracking",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663651644589/cNZFBcai4VvVZ9Us6eXbuZ/fitness-tracker-category-UCmKXj65PpLEG8nAygtcUJ.webp",
    productCount: 4,
  },
  {
    id: "smart-rings",
    name: "Smart Rings",
    description: "Discreet ring-form health trackers with advanced biometric sensors",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663651644589/cNZFBcai4VvVZ9Us6eXbuZ/smart-ring-category-XsL2zS3BjHhGtUciiyt9UJ.webp",
    productCount: 3,
  },
  {
    id: "smart-glasses",
    name: "Smart Glasses",
    description: "AI-powered eyewear with cameras, audio, and augmented reality features",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/310519663651644589/cNZFBcai4VvVZ9Us6eXbuZ/ar-glasses-category-gNZrUvSeoACDzBCrWXLhBw.webp",
    productCount: 2,
  },
  {
    id: "vr-headsets",
    name: "Cell Phone Virtual Reality",
    description: "VR headsets and virtual reality devices for immersive experiences",
    image: "https://images.unsplash.com/photo-1617638924702-92f37fcb0f6d?w=600&q=80",
    productCount: 2,
  },
  {
    id: "kids-wearables",
    name: "Wearable tech for Kids",
    description: "Safe, fun, and educational wearable technology designed for children",
    image: "https://images.unsplash.com/photo-1609708536965-59e6a8e9e341?w=600&q=80",
    productCount: 3,
  },
  {
    id: "pet-wearables",
    name: "Tech for your Pets",
    description: "GPS trackers, activity monitors, and smart devices for your furry friends",
    image: "https://images.unsplash.com/photo-1633722715463-d30628519d00?w=600&q=80",
    productCount: 3,
  },
  {
    id: "bluetooth-headsets",
    name: "Cell Phone Bluetooth Headsets",
    description: "Wireless headsets for calls, audio, and hands-free communication",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    productCount: 3,
  },
  {
    id: "pendants",
    name: "Wearable Tech Pendants",
    description: "Stylish pendant-form wearables for health tracking and notifications",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    productCount: 2,
  },
  {
    id: "hats-caps",
    name: "Bluetooth Capable Hats & Caps",
    description: "Smart hats and caps with integrated Bluetooth and audio features",
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80",
    productCount: 2,
  },
  {
    id: "arm-wristbands",
    name: "Wearable Tech Arm & Wristbands",
    description: "Advanced arm bands and wristbands for fitness and health monitoring",
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80",
    productCount: 3,
  },
  {
    id: "assistive-tech",
    name: "Assistive & Specialty Wearables",
    description: "Specialized wearables for accessibility, translation, and unique needs",
    image: "https://images.unsplash.com/photo-1576091160550-112173f7f869?w=600&q=80",
    productCount: 4,
  },
];

export const products: Product[] = [
  // ─── SMARTWATCHES & ACCESSORIES ───────────────────────────────────────────
  {
    id: "fitbit-versa-4",
    name: "Google Fitbit Versa 4",
    brand: "Google Fitbit",
    category: "smartwatches",
    price: 299,
    originalPrice: 349,
    rating: 4.5,
    reviewCount: 2847,
    badge: "editors-choice",
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Fitbit-Smartwatch-Readiness-Exercise-Tracking/dp/B0B75TVZZZ?tag=weyoowte-20",
    shortDescription: "Full-featured fitness smartwatch with GPS, heart rate monitoring, and 40+ exercise modes.",
    pros: [
      "Built-in GPS",
      "Daily Readiness score",
      "40+ exercise modes",
      "7-day battery life",
      "Water resistant",
    ],
    cons: [
      "Requires Fitbit Premium for full features",
      "Limited app ecosystem",
      "No offline maps",
    ],
    specs: {
      "Display": "1.34\" AMOLED",
      "Battery Life": "Up to 7 days",
      "GPS": "Built-in GPS",
      "Health Sensors": "Heart Rate, SpO2, EDA",
      "Water Resistance": "5ATM",
      "Connectivity": "Wi-Fi, Bluetooth",
      "OS": "Fitbit OS",
    },
    score: { design: 4.3, performance: 4.5, battery: 4.4, value: 4.6, features: 4.5 },
    featured: true,
  },
  {
    id: "fitbit-inspire-3",
    name: "Google Fitbit Inspire 3",
    brand: "Google Fitbit",
    category: "smartwatches",
    price: 149,
    rating: 4.4,
    reviewCount: 1234,
    badge: "best-value",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Fitbit-Management-Intensity-Tracking-Midnight/dp/B0B75RC9C3?tag=weyoowte-20",
    shortDescription: "Affordable fitness tracker with OLED display, sleep tracking, and 10-day battery.",
    pros: [
      "Affordable price",
      "Bright OLED display",
      "Excellent sleep tracking",
      "10-day battery life",
      "Works with iOS and Android",
    ],
    cons: [
      "No GPS",
      "Limited smart features",
      "Requires Fitbit Premium for insights",
    ],
    specs: {
      "Display": "0.64\" OLED",
      "Battery Life": "Up to 10 days",
      "GPS": "No (connected GPS only)",
      "Health Sensors": "Heart Rate, SpO2, Sleep",
      "Water Resistance": "5ATM",
      "Connectivity": "Bluetooth 5.0",
      "Subscription": "Fitbit Premium (optional)",
    },
    score: { design: 4.2, performance: 4.3, battery: 4.6, value: 4.8, features: 3.9 },
  },
  {
    id: "samsung-galaxy-watch-8",
    name: "Samsung Galaxy Watch 8",
    brand: "Samsung",
    category: "smartwatches",
    price: 399,
    rating: 4.6,
    reviewCount: 3421,
    badge: "editors-choice",
    image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Samsung-Fitness-Monitor-Tracker-Battery/dp/B0DDV4LTW7?tag=weyoowte-20",
    shortDescription: "Premium Android smartwatch with AI features, health coaching, and rotating bezel.",
    pros: [
      "Rotating bezel navigation",
      "Excellent health tracking",
      "AI sleep coaching",
      "40-hour battery",
      "Premium build quality",
    ],
    cons: [
      "Best features require Samsung phone",
      "Wear OS can be cluttered",
      "Expensive",
    ],
    specs: {
      "Display": "1.3\" AMOLED",
      "Battery Life": "Up to 40 hours",
      "GPS": "GPS, GLONASS, BeiDou",
      "Health Sensors": "BioActive (ECG, Body Composition, SpO2)",
      "Water Resistance": "5ATM + IP68",
      "Connectivity": "Wi-Fi, Bluetooth 5.3, LTE",
      "OS": "Wear OS 5",
    },
    score: { design: 4.5, performance: 4.6, battery: 4.8, value: 4.2, features: 4.8 },
  },
  {
    id: "generic-smartwatch",
    name: "Smart Watch for Men Women",
    brand: "Generic",
    category: "smartwatches",
    price: 89,
    rating: 4.2,
    reviewCount: 856,
    badge: "best-value",
    image: "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Bluetooth-Smartwatch-Fitness-Monitor-Waterproof/dp/B0FXLGDGJH?tag=weyoowte-20",
    shortDescription: "Budget-friendly smartwatch with Bluetooth calling, fitness tracking, and 100+ sports modes.",
    pros: [
      "Very affordable",
      "Bluetooth calling",
      "100+ sports modes",
      "HD touchscreen",
      "Heart rate and SpO2 monitoring",
    ],
    cons: [
      "Limited battery life",
      "Basic app ecosystem",
      "Less reliable tracking",
    ],
    specs: {
      "Display": "1.85\" HD DIY Dial",
      "Battery Life": "Up to 7 days",
      "GPS": "No",
      "Health Sensors": "Heart Rate, SpO2, Steps",
      "Water Resistance": "IP67",
      "Connectivity": "Bluetooth 5.0",
      "Sports Modes": "100+",
    },
    score: { design: 3.8, performance: 3.9, battery: 4.1, value: 4.7, features: 4.0 },
  },
  {
    id: "smartwatch-band-pack",
    name: "Smart Watch Band Pack (Multiple Colors)",
    brand: "Generic",
    category: "smartwatches",
    price: 29,
    rating: 4.3,
    reviewCount: 567,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Smart-Watch-Accessories/b?ie=UTF8&node=8876986011?tag=weyoowte-20",
    shortDescription: "Pack of replacement smartwatch bands in various colors and materials.",
    pros: [
      "Multiple color options",
      "Affordable",
      "Easy to swap",
      "Durable materials",
    ],
    cons: [
      "May not fit all watch models",
      "Quality varies",
    ],
    specs: {
      "Material": "Silicone/Leather",
      "Colors": "Multiple",
      "Compatibility": "Most smartwatches",
      "Quantity": "3-5 bands per pack",
    },
    score: { design: 4.2, performance: 4.0, battery: 0, value: 4.5, features: 3.5 },
  },

  // ─── SPORT ACTIVITY TRACKERS ───────────────────────────────────────────
  {
    id: "fitbit-charge-6",
    name: "Google Fitbit Charge 6",
    brand: "Google Fitbit",
    category: "fitness-trackers",
    price: 199,
    originalPrice: 249,
    rating: 4.6,
    reviewCount: 3201,
    badge: "editors-choice",
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Fitbit-Advanced-Fitness-Management-Tracking/dp/B0CC62ZG1M?tag=weyoowte-20",
    shortDescription: "Advanced fitness tracker with built-in GPS, ECG, and stress management tools.",
    pros: [
      "Built-in GPS",
      "ECG and AFib detection",
      "Stress management tools",
      "7-day battery",
      "Excellent accuracy",
    ],
    cons: [
      "Requires Fitbit Premium",
      "Limited smart features",
      "No offline maps",
    ],
    specs: {
      "Display": "1.04\" AMOLED",
      "Battery Life": "Up to 7 days",
      "GPS": "Built-in GPS",
      "Health Sensors": "Heart Rate, ECG, SpO2, EDA, Skin Temperature",
      "Water Resistance": "5ATM",
      "Connectivity": "Wi-Fi, Bluetooth",
      "Stress Tools": "EDA, Guided Breathing",
    },
    score: { design: 4.4, performance: 4.6, battery: 4.5, value: 4.5, features: 4.7 },
    featured: true,
  },
  {
    id: "troty-fitness-tracker",
    name: "TROTY Fitness Tracker",
    brand: "TROTY",
    category: "fitness-trackers",
    price: 79,
    rating: 4.1,
    reviewCount: 892,
    badge: "best-value",
    image: "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/TROTY-Fitness-Tracker-Monitor-Activity/dp/B0FNQZZYCX?tag=weyoowte-20",
    shortDescription: "Budget fitness tracker with 24/7 heart rate, blood oxygen, and blood pressure monitoring.",
    pros: [
      "Very affordable",
      "24/7 monitoring",
      "Blood pressure tracking",
      "Waterproof design",
      "Long battery life",
    ],
    cons: [
      "Limited app support",
      "Basic display",
      "Less accurate tracking",
    ],
    specs: {
      "Display": "1.10\" AMOLED",
      "Battery Life": "Up to 14 days",
      "GPS": "No",
      "Health Sensors": "Heart Rate, Blood Oxygen, Blood Pressure, Temperature",
      "Water Resistance": "IP68",
      "Connectivity": "Bluetooth 5.0",
      "Sleep Tracking": "Yes",
    },
    score: { design: 3.9, performance: 4.0, battery: 4.5, value: 4.6, features: 4.1 },
  },
  {
    id: "garmin-vivosmart",
    name: "Garmin Vivosmart Band",
    brand: "Garmin",
    category: "fitness-trackers",
    price: 149,
    rating: 4.4,
    reviewCount: 1567,
    image: "https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Garmin-Vivosmart/s?k=garmin+vivosmart?tag=weyoowte-20",
    shortDescription: "Slim fitness band with Garmin's proven health tracking and 7-day battery.",
    pros: [
      "Slim and lightweight",
      "Garmin's trusted algorithms",
      "Pulse Ox monitoring",
      "7-day battery",
      "Durable build",
    ],
    cons: [
      "No GPS",
      "Limited display",
      "Basic smart features",
    ],
    specs: {
      "Display": "0.64\" OLED",
      "Battery Life": "Up to 7 days",
      "GPS": "No",
      "Health Sensors": "Heart Rate, Pulse Ox, Stress",
      "Water Resistance": "5ATM",
      "Connectivity": "Bluetooth",
      "Sleep Tracking": "Yes",
    },
    score: { design: 4.3, performance: 4.4, battery: 4.6, value: 4.4, features: 4.2 },
  },
  {
    id: "withings-scanwatch",
    name: "Withings ScanWatch Hybrid",
    brand: "Withings",
    category: "fitness-trackers",
    price: 279,
    rating: 4.5,
    reviewCount: 1203,
    badge: "new",
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Withings-ScanWatch/s?k=withings+scanwatch?tag=weyoowte-20",
    shortDescription: "Medical-grade hybrid smartwatch with ECG, SpO2, and classic analog watch design.",
    pros: [
      "Classic watch aesthetic",
      "Medical-grade ECG",
      "30-day battery",
      "Sleep apnea detection",
      "Elegant design",
    ],
    cons: [
      "Limited smart features",
      "Expensive",
      "Small display",
    ],
    specs: {
      "Display": "Analog + small digital",
      "Battery Life": "Up to 30 days",
      "GPS": "No",
      "Health Sensors": "ECG, SpO2, Heart Rate, Sleep",
      "Water Resistance": "5ATM",
      "Connectivity": "Bluetooth, Wi-Fi",
      "Medical Grade": "Yes",
    },
    score: { design: 4.7, performance: 4.5, battery: 4.9, value: 4.0, features: 4.3 },
  },

  // ─── SMART RINGS ───────────────────────────────────────────
  {
    id: "samsung-galaxy-ring",
    name: "Samsung Galaxy Ring",
    brand: "Samsung",
    category: "smart-rings",
    price: 399,
    rating: 4.6,
    reviewCount: 1876,
    badge: "editors-choice",
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Samsung-Fitness-Monitor-Tracker-Battery/dp/B0DDV4LTW7?tag=weyoowte-20",
    shortDescription: "Advanced smart ring with 18 sensors, AI insights, and 7-day battery life.",
    pros: [
      "Most accurate sleep tracking",
      "7-day battery",
      "18 sensors",
      "AI-powered insights",
      "Discreet design",
    ],
    cons: [
      "Expensive",
      "Requires Samsung phone for full features",
      "Limited third-party app support",
    ],
    specs: {
      "Sensors": "18 biometric sensors",
      "Battery Life": "Up to 7 days",
      "Materials": "Titanium",
      "Water Resistance": "5ATM",
      "Connectivity": "Bluetooth 5.4",
      "Sizing": "Multiple sizes available",
      "Health Tracking": "Sleep, Heart Rate, Temperature, SpO2",
    },
    score: { design: 4.8, performance: 4.7, battery: 4.6, value: 4.0, features: 4.8 },
    featured: true,
  },
  {
    id: "ringconn-gen-2",
    name: "RingConn Gen 2 Smart Ring",
    brand: "RingConn",
    category: "smart-rings",
    price: 299,
    rating: 4.4,
    reviewCount: 892,
    badge: "best-value",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/smart-ring-health-tracker/s?k=smart+ring+health+tracker?tag=weyoowte-20",
    shortDescription: "No-subscription smart ring with 12-day battery and stress/women's health tracking.",
    pros: [
      "No app subscription required",
      "12-day battery",
      "Women's health tracking",
      "Stress monitoring",
      "Affordable",
    ],
    cons: [
      "Fewer sensors than competitors",
      "Limited app ecosystem",
      "Smaller display",
    ],
    specs: {
      "Sensors": "8 biometric sensors",
      "Battery Life": "Up to 12 days",
      "Materials": "Titanium",
      "Water Resistance": "IP68",
      "Connectivity": "Bluetooth 5.0",
      "Subscription": "None required",
      "Health Tracking": "Sleep, Heart Rate, Stress, Women's Health",
    },
    score: { design: 4.3, performance: 4.4, battery: 4.7, value: 4.6, features: 4.3 },
  },
  {
    id: "oura-ring-gen-3",
    name: "Oura Ring Generation 3",
    brand: "Oura",
    category: "smart-rings",
    price: 349,
    rating: 4.5,
    reviewCount: 1234,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Oura-Generation-Readiness-Tracking-Midnight/s?k=oura+ring?tag=weyoowte-20",
    shortDescription: "Premium health tracking ring with readiness score and detailed sleep insights.",
    pros: [
      "Excellent sleep insights",
      "Readiness score",
      "10-day battery",
      "Premium materials",
      "Accurate tracking",
    ],
    cons: [
      "Requires subscription",
      "Expensive",
      "Limited smart features",
    ],
    specs: {
      "Sensors": "9 biometric sensors",
      "Battery Life": "Up to 10 days",
      "Materials": "Titanium",
      "Water Resistance": "IP68",
      "Connectivity": "Bluetooth 5.0",
      "Subscription": "Oura membership required",
      "Health Tracking": "Sleep, Heart Rate, Temperature, Readiness",
    },
    score: { design: 4.6, performance: 4.5, battery: 4.6, value: 4.1, features: 4.5 },
  },

  // ─── SMART GLASSES ───────────────────────────────────────────
  {
    id: "xreal-air-4-pro",
    name: "XReal Air 4 Pro AR Glasses",
    brand: "XReal",
    category: "smart-glasses",
    price: 649,
    rating: 4.5,
    reviewCount: 567,
    badge: "new",
    image: "https://images.unsplash.com/photo-1617638924702-92f37fcb0f6d?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/x-real-air-ar-glasses/s?k=x+real+air+ar+glasses?tag=weyoowte-20",
    shortDescription: "Premium AR glasses with 201\" virtual display, HDR10, and 120Hz 3D support.",
    pros: [
      "Massive 201\" virtual display",
      "HDR10 support",
      "120Hz 3D movies",
      "USB-C plug & play",
      "Works with multiple devices",
    ],
    cons: [
      "Very expensive",
      "Requires compatible device",
      "Limited app ecosystem",
    ],
    specs: {
      "Display": "201\" virtual screen",
      "Resolution": "1080p OLED",
      "Refresh Rate": "120Hz",
      "Compatibility": "iPhone, Android, Switch, PS5",
      "Connection": "USB-C",
      "Weight": "Lightweight design",
      "Features": "HDR10, 3D movies, gaming",
    },
    score: { design: 4.6, performance: 4.5, battery: 0, value: 3.8, features: 4.7 },
  },
  {
    id: "denash-ar-glasses",
    name: "Denash AR Glasses 1080P OLED",
    brand: "Denash",
    category: "smart-glasses",
    price: 399,
    rating: 4.3,
    reviewCount: 423,
    badge: "best-value",
    image: "https://images.unsplash.com/photo-1617638924702-92f37fcb0f6d?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/ar-glasses-android/s?k=ar+glasses+for+android?tag=weyoowte-20",
    shortDescription: "Affordable AR glasses with 1080P OLED display, 3000-nit brightness, and myopia adjustment.",
    pros: [
      "Affordable AR glasses",
      "Ultra-bright 3000 nits",
      "Myopia adjustment (0-600°)",
      "400\" virtual screen",
      "Built-in speakers",
    ],
    cons: [
      "Limited app support",
      "Android only",
      "Heavier than competitors",
    ],
    specs: {
      "Display": "1080P OLED",
      "Brightness": "3000 nits",
      "Virtual Screen": "Up to 400\"",
      "Myopia Adjustment": "0-600°",
      "Compatibility": "Android devices",
      "Audio": "Built-in speakers",
      "Features": "Immersive XR experience",
    },
    score: { design: 4.2, performance: 4.3, battery: 0, value: 4.5, features: 4.4 },
  },

  // ─── CELL PHONE VIRTUAL REALITY ───────────────────────────────────────────
  {
    id: "vr-headset-generic",
    name: "Universal VR Headset for Smartphones",
    brand: "Generic",
    category: "vr-headsets",
    price: 49,
    rating: 4.0,
    reviewCount: 1234,
    badge: "best-value",
    image: "https://images.unsplash.com/photo-1609708536965-59e6a8e9e341?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Virtual-Reality-Headset-Smartphone-Compatible/s?k=vr+headset?tag=weyoowte-20",
    shortDescription: "Affordable VR headset compatible with most smartphones for immersive gaming and videos.",
    pros: [
      "Very affordable",
      "Works with most phones",
      "Comfortable fit",
      "Good field of view",
      "Easy to use",
    ],
    cons: [
      "Basic optics",
      "No motion controls",
      "Limited app support",
    ],
    specs: {
      "Compatibility": "Most smartphones",
      "Field of View": "90-100°",
      "Focus Adjustment": "Yes",
      "Material": "Plastic/Foam",
      "Weight": "Lightweight",
      "Features": "360° videos, games",
    },
    score: { design: 3.8, performance: 3.9, battery: 0, value: 4.6, features: 3.7 },
  },
  {
    id: "rayneo-air-4-pro",
    name: "RayNeo Air 4 Pro AR/XR Glasses",
    brand: "RayNeo",
    category: "vr-headsets",
    price: 799,
    rating: 4.4,
    reviewCount: 356,
    badge: "new",
    image: "https://images.unsplash.com/photo-1609708536965-59e6a8e9e341?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Video-Display-Glasses-4-Stars-Up/s?rh=n%3A3379654011?tag=weyoowte-20",
    shortDescription: "Premium AR/XR glasses with 201\" HDR10 display, 120Hz 3D, and plug-and-play compatibility.",
    pros: [
      "Massive 201\" display",
      "HDR10 support",
      "120Hz 3D support",
      "USB-C plug & play",
      "Premium build",
    ],
    cons: [
      "Very expensive",
      "Limited app ecosystem",
      "Requires compatible device",
    ],
    specs: {
      "Display": "201\" virtual screen",
      "Resolution": "1080p",
      "Refresh Rate": "120Hz",
      "Compatibility": "iPhone, Android, Switch, PS5",
      "Connection": "USB-C",
      "Features": "HDR10, 3D movies, gaming",
    },
    score: { design: 4.5, performance: 4.4, battery: 0, value: 3.9, features: 4.6 },
  },

  // ─── WEARABLE TECH FOR KIDS ───────────────────────────────────────────
  {
    id: "kids-smartwatch-puzzle",
    name: "Kids Smart Watch with Puzzle Games",
    brand: "Generic",
    category: "kids-wearables",
    price: 59,
    rating: 4.2,
    reviewCount: 892,
    badge: "best-value",
    image: "https://images.unsplash.com/photo-1633722715463-d30628519d00?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Childrens-Smart-Watches/s?k=Children%27s+Smart+Watches?tag=weyoowte-20",
    shortDescription: "Fun kids smartwatch with 12 puzzle games, HD touchscreen, and fitness tracking.",
    pros: [
      "Educational games",
      "HD touchscreen",
      "Fitness tracking",
      "Waterproof design",
      "Affordable",
    ],
    cons: [
      "Limited battery",
      "Basic features",
      "Durability concerns",
    ],
    specs: {
      "Display": "1.83\" HD Touchscreen",
      "Games": "12 puzzle games",
      "Battery Life": "Up to 5 days",
      "Water Resistance": "IP67",
      "Features": "Pedometer, alarm, flashlight",
      "Age Range": "6-12 years",
      "Connectivity": "Bluetooth",
    },
    score: { design: 4.1, performance: 4.0, battery: 4.0, value: 4.5, features: 4.2 },
  },
  {
    id: "4g-kids-smartwatch",
    name: "4G Kids Smart Watch with Video Call",
    brand: "Generic",
    category: "kids-wearables",
    price: 149,
    rating: 4.3,
    reviewCount: 567,
    image: "https://images.unsplash.com/photo-1633722715463-d30628519d00?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/4g-lte-kids-smart-watch/s?k=4g+lte+kids+smart+watch?tag=weyoowte-20",
    shortDescription: "Advanced 4G kids smartwatch with video calls, GPS tracking, and SOS button.",
    pros: [
      "4G connectivity",
      "Video calling",
      "GPS tracking",
      "SOS emergency button",
      "Parent app control",
    ],
    cons: [
      "Requires SIM card",
      "Monthly data costs",
      "Larger size",
    ],
    specs: {
      "Display": "1.4\" HD Touchscreen",
      "Connectivity": "4G LTE",
      "GPS": "Real-time tracking",
      "Features": "Video call, SOS, music",
      "Battery Life": "Up to 3 days",
      "Age Range": "4-12 years",
      "Parent Control": "Mobile app",
    },
    score: { design: 4.2, performance: 4.3, battery: 3.8, value: 4.1, features: 4.5 },
  },
  {
    id: "garmin-bounce-2",
    name: "Garmin Bounce 2 Kids Smartwatch",
    brand: "Garmin",
    category: "kids-wearables",
    price: 199,
    rating: 4.4,
    reviewCount: 734,
    badge: "editors-choice",
    image: "https://images.unsplash.com/photo-1633722715463-d30628519d00?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/stores/Garmin/page/A8DB24FD-BC99-49D1-B0FC-36F35ABC6B95?tag=weyoowte-20",
    shortDescription: "Premium kids smartwatch by Garmin with calling, messaging, and location tracking.",
    pros: [
      "Garmin reliability",
      "Calling and messaging",
      "GPS tracking",
      "Durable design",
      "Parent controls",
    ],
    cons: [
      "Expensive for kids watch",
      "Requires subscription",
      "Limited app support",
    ],
    specs: {
      "Display": "1.3\" AMOLED",
      "Connectivity": "4G LTE",
      "GPS": "Real-time tracking",
      "Features": "Calling, messaging, SOS",
      "Battery Life": "Up to 2 days",
      "Age Range": "6-12 years",
      "Durability": "MIL-STD-810",
    },
    score: { design: 4.4, performance: 4.4, battery: 3.9, value: 4.0, features: 4.5 },
  },

  // ─── TECH FOR YOUR PETS ───────────────────────────────────────────
  {
    id: "tractive-dog-gps",
    name: "Tractive XL Smart Dog GPS Tracker",
    brand: "Tractive",
    category: "pet-wearables",
    price: 129,
    rating: 4.5,
    reviewCount: 1876,
    badge: "editors-choice",
    image: "https://images.unsplash.com/photo-1633722715463-d30628519d00?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/dog-tracking-collar/s?k=dog+tracking+collar?tag=weyoowte-20",
    shortDescription: "Real-time GPS tracker for dogs with virtual fence and vital signs monitoring.",
    pros: [
      "Real-time tracking",
      "Virtual fence alerts",
      "Heart rate monitoring",
      "1-month battery",
      "Waterproof design",
    ],
    cons: [
      "Requires subscription",
      "Larger size",
      "Expensive",
    ],
    specs: {
      "GPS": "Real-time tracking",
      "Battery Life": "Up to 1 month",
      "Water Resistance": "IP67",
      "Features": "Virtual fence, vital signs",
      "Connectivity": "LTE",
      "Weight": "Suitable for large dogs",
      "App": "Mobile app included",
    },
    score: { design: 4.4, performance: 4.5, battery: 4.7, value: 4.2, features: 4.6 },
  },
  {
    id: "pawfit-lite-gps",
    name: "Pawfit Lite for Dogs 4G GPS Tracker",
    brand: "Pawfit",
    category: "pet-wearables",
    price: 99,
    rating: 4.3,
    reviewCount: 654,
    badge: "best-value",
    image: "https://images.unsplash.com/photo-1633722715463-d30628519d00?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/dog-activity-tracker/s?k=dog+activity+tracker?tag=weyoowte-20",
    shortDescription: "Affordable 4G GPS tracker for dogs with activity monitoring and unlimited range.",
    pros: [
      "Affordable",
      "Unlimited range",
      "Activity tracking",
      "Real-time alerts",
      "Lightweight design",
    ],
    cons: [
      "Requires subscription",
      "Battery life moderate",
      "Limited features",
    ],
    specs: {
      "GPS": "Real-time tracking",
      "Battery Life": "Up to 5 days",
      "Water Resistance": "IP67",
      "Features": "Activity monitoring, alerts",
      "Connectivity": "4G LTE",
      "Range": "Unlimited",
      "App": "Mobile app included",
    },
    score: { design: 4.2, performance: 4.3, battery: 4.2, value: 4.5, features: 4.3 },
  },
  {
    id: "cat-tracker-collar",
    name: "Cat Tracker with Collar (GPS)",
    brand: "Generic",
    category: "pet-wearables",
    price: 79,
    rating: 4.1,
    reviewCount: 423,
    image: "https://images.unsplash.com/photo-1633722715463-d30628519d00?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/animal-tracker/s?k=animal+tracker?tag=weyoowte-20",
    shortDescription: "GPS tracker for cats with no monthly fee, waterproof design, and 365-day battery.",
    pros: [
      "No monthly fees",
      "365-day battery",
      "Waterproof design",
      "Affordable",
      "Real-time tracking",
    ],
    cons: [
      "Limited range",
      "Bulky for cats",
      "Basic features",
    ],
    specs: {
      "GPS": "Real-time tracking",
      "Battery Life": "Up to 1 year",
      "Water Resistance": "IP67",
      "Features": "Location history",
      "Connectivity": "Bluetooth",
      "Subscription": "None required",
      "Size": "Compact design",
    },
    score: { design: 3.9, performance: 4.0, battery: 4.8, value: 4.6, features: 3.8 },
  },

  // ─── CELL PHONE BLUETOOTH HEADSETS ───────────────────────────────────────────
  {
    id: "jbl-tune-520bt",
    name: "JBL Tune 520BT Wireless Headphones",
    brand: "JBL",
    category: "bluetooth-headsets",
    price: 89,
    rating: 4.3,
    reviewCount: 2134,
    badge: "best-value",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/bluetooth-headphones/s?k=bluetooth+headphones?tag=weyoowte-20",
    shortDescription: "Lightweight wireless headphones with 57-hour battery and comfortable design.",
    pros: [
      "57-hour battery life",
      "Lightweight and comfortable",
      "Foldable design",
      "Affordable",
      "Good sound quality",
    ],
    cons: [
      "Basic features",
      "No noise cancellation",
      "Plastic build",
    ],
    specs: {
      "Battery Life": "Up to 57 hours",
      "Connectivity": "Bluetooth 5.3",
      "Weight": "Lightweight",
      "Design": "Foldable",
      "Audio": "40mm drivers",
      "Microphone": "Built-in",
      "Charging": "USB-C",
    },
    score: { design: 4.2, performance: 4.3, battery: 4.8, value: 4.5, features: 4.1 },
  },
  {
    id: "trucker-bluetooth-headset",
    name: "Trucker Bluetooth Headset Wireless",
    brand: "Generic",
    category: "bluetooth-headsets",
    price: 79,
    rating: 4.2,
    reviewCount: 876,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Bluetooth-Headset-Cell-Phone/s?k=Bluetooth+Headset+for+Cell+Phone?tag=weyoowte-20",
    shortDescription: "Professional trucker headset with noise cancelling, mute button, and 55-hour battery.",
    pros: [
      "Noise cancelling",
      "55-hour battery",
      "Mute button",
      "Professional design",
      "Comfortable fit",
    ],
    cons: [
      "Bulky design",
      "Limited features",
      "Mono audio",
    ],
    specs: {
      "Battery Life": "Up to 55 hours",
      "Connectivity": "Bluetooth 5.0",
      "Features": "Noise cancelling, mute",
      "Design": "Over-ear",
      "Microphone": "Boom microphone",
      "Use Case": "Trucking, calls",
      "Charging": "Micro USB",
    },
    score: { design: 4.0, performance: 4.2, battery: 4.7, value: 4.3, features: 4.1 },
  },
  {
    id: "translator-earbuds",
    name: "AI Language Translator Earbuds",
    brand: "Generic",
    category: "bluetooth-headsets",
    price: 99,
    rating: 4.1,
    reviewCount: 567,
    badge: "new",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/translator-earbuds/s?k=translator+earbuds?tag=weyoowte-20",
    shortDescription: "Real-time translation earbuds supporting 164 languages with 6 translation modes.",
    pros: [
      "164 languages supported",
      "Real-time translation",
      "6 translation modes",
      "40-hour battery",
      "Affordable",
    ],
    cons: [
      "Translation accuracy varies",
      "Requires internet",
      "Limited audio quality",
    ],
    specs: {
      "Languages": "164 supported",
      "Translation Modes": "6 modes",
      "Battery Life": "Up to 40 hours",
      "Connectivity": "Bluetooth 5.4",
      "Features": "Real-time translation",
      "Audio Quality": "Stereo",
      "Charging": "USB-C",
    },
    score: { design: 4.0, performance: 4.1, battery: 4.6, value: 4.2, features: 4.3 },
  },

  // ─── WEARABLE TECH PENDANTS ───────────────────────────────────────────
  {
    id: "emergency-pendant",
    name: "Personal Emergency Alert Pendant",
    brand: "Generic",
    category: "pendants",
    price: 129,
    rating: 4.4,
    reviewCount: 734,
    badge: "editors-choice",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Personal-Emergency-Alert-Pendant-Wearable/s?k=emergency+pendant?tag=weyoowte-20",
    shortDescription: "Wearable emergency alert pendant with fall detection and 24/7 monitoring.",
    pros: [
      "Fall detection",
      "24/7 monitoring",
      "Waterproof design",
      "Easy to use",
      "Emergency response",
    ],
    cons: [
      "Requires subscription",
      "Limited features",
      "Bulky design",
    ],
    specs: {
      "Features": "Fall detection, SOS button",
      "Monitoring": "24/7 professional",
      "Water Resistance": "IP67",
      "Battery Life": "Up to 5 days",
      "Connectivity": "Cellular",
      "Subscription": "Monthly monitoring",
      "Design": "Pendant style",
    },
    score: { design: 4.2, performance: 4.4, battery: 4.3, value: 4.2, features: 4.5 },
  },
  {
    id: "health-monitor-pendant",
    name: "Health Monitor Pendant with ECG",
    brand: "Generic",
    category: "pendants",
    price: 199,
    rating: 4.3,
    reviewCount: 456,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Health-Monitor-Pendant-Wearable/s?k=health+pendant?tag=weyoowte-20",
    shortDescription: "Stylish health monitoring pendant with ECG, heart rate, and temperature tracking.",
    pros: [
      "Medical-grade ECG",
      "Heart rate monitoring",
      "Temperature tracking",
      "Stylish design",
      "Continuous monitoring",
    ],
    cons: [
      "Expensive",
      "Requires charging",
      "Limited app support",
    ],
    specs: {
      "Health Sensors": "ECG, Heart Rate, Temperature",
      "Battery Life": "Up to 7 days",
      "Water Resistance": "IP67",
      "Design": "Pendant style",
      "Connectivity": "Bluetooth",
      "Monitoring": "Continuous",
      "App": "Mobile app included",
    },
    score: { design: 4.4, performance: 4.3, battery: 4.2, value: 4.1, features: 4.4 },
  },

  // ─── BLUETOOTH CAPABLE HATS & CAPS ───────────────────────────────────────────
  {
    id: "bluetooth-beanie",
    name: "Bluetooth Beanie Winter Hat",
    brand: "Generic",
    category: "hats-caps",
    price: 49,
    rating: 4.1,
    reviewCount: 567,
    badge: "best-value",
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Bluetooth-Beanie-Winter-Hat/s?k=bluetooth+beanie?tag=weyoowte-20",
    shortDescription: "Warm winter beanie with integrated Bluetooth speakers and microphone.",
    pros: [
      "Warm and comfortable",
      "Built-in speakers",
      "Microphone for calls",
      "Affordable",
      "Easy to use",
    ],
    cons: [
      "Limited battery",
      "Audio quality average",
      "Washability concerns",
    ],
    specs: {
      "Material": "Wool blend",
      "Connectivity": "Bluetooth 5.0",
      "Battery Life": "Up to 8 hours",
      "Features": "Speakers, microphone",
      "Design": "Winter beanie",
      "Charging": "Micro USB",
      "Colors": "Multiple",
    },
    score: { design: 4.0, performance: 4.0, battery: 4.1, value: 4.4, features: 4.0 },
  },
  {
    id: "bluetooth-baseball-cap",
    name: "Bluetooth Baseball Cap with Speakers",
    brand: "Generic",
    category: "hats-caps",
    price: 59,
    rating: 4.2,
    reviewCount: 423,
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Bluetooth-Baseball-Cap-Speakers/s?k=bluetooth+cap?tag=weyoowte-20",
    shortDescription: "Stylish baseball cap with integrated Bluetooth audio and hands-free calling.",
    pros: [
      "Stylish design",
      "Built-in speakers",
      "Hands-free calling",
      "Adjustable fit",
      "Affordable",
    ],
    cons: [
      "Limited battery",
      "Audio quality basic",
      "Not waterproof",
    ],
    specs: {
      "Material": "Cotton blend",
      "Connectivity": "Bluetooth 5.0",
      "Battery Life": "Up to 6 hours",
      "Features": "Speakers, microphone",
      "Design": "Baseball cap",
      "Charging": "Micro USB",
      "Colors": "Multiple",
    },
    score: { design: 4.1, performance: 4.0, battery: 3.9, value: 4.3, features: 4.0 },
  },

  // ─── WEARABLE TECH ARM & WRISTBANDS ───────────────────────────────────────────
  {
    id: "armband-phone-holder",
    name: "Sports Armband Phone Holder",
    brand: "Generic",
    category: "arm-wristbands",
    price: 29,
    rating: 4.2,
    reviewCount: 1234,
    badge: "best-value",
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Sports-Armband-Phone-Holder/s?k=armband+phone?tag=weyoowte-20",
    shortDescription: "Adjustable sports armband for running and workouts with secure phone holder.",
    pros: [
      "Very affordable",
      "Secure fit",
      "Adjustable",
      "Lightweight",
      "Works with most phones",
    ],
    cons: [
      "No tech features",
      "Basic materials",
      "Limited durability",
    ],
    specs: {
      "Material": "Neoprene",
      "Compatibility": "Most phones",
      "Adjustability": "Adjustable strap",
      "Features": "Reflective design",
      "Weight": "Lightweight",
      "Use Case": "Running, workouts",
      "Warranty": "1 year",
    },
    score: { design: 4.0, performance: 4.1, battery: 0, value: 4.6, features: 3.5 },
  },
  {
    id: "smart-wristband-health",
    name: "Smart Wristband Health Monitor",
    brand: "Generic",
    category: "arm-wristbands",
    price: 89,
    rating: 4.3,
    reviewCount: 876,
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Smart-Wristband-Health-Monitor/s?k=smart+wristband?tag=weyoowte-20",
    shortDescription: "Advanced wristband with continuous health monitoring and activity tracking.",
    pros: [
      "Continuous monitoring",
      "Activity tracking",
      "Heart rate sensor",
      "Affordable",
      "Comfortable fit",
    ],
    cons: [
      "Limited smart features",
      "Basic display",
      "Moderate battery",
    ],
    specs: {
      "Sensors": "Heart rate, temperature",
      "Battery Life": "Up to 10 days",
      "Water Resistance": "IP67",
      "Features": "Activity tracking, sleep",
      "Connectivity": "Bluetooth",
      "Display": "LED indicators",
      "Material": "Silicone",
    },
    score: { design: 4.1, performance: 4.2, battery: 4.4, value: 4.4, features: 4.2 },
  },
  {
    id: "compression-wristband",
    name: "Compression Wristband with Temperature",
    brand: "Generic",
    category: "arm-wristbands",
    price: 49,
    rating: 4.0,
    reviewCount: 345,
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Compression-Wristband/s?k=compression+wristband?tag=weyoowte-20",
    shortDescription: "Medical-grade compression wristband with temperature therapy and pain relief.",
    pros: [
      "Medical-grade compression",
      "Temperature therapy",
      "Pain relief",
      "Affordable",
      "Reusable",
    ],
    cons: [
      "No smart features",
      "Limited durability",
      "One size",
    ],
    specs: {
      "Material": "Neoprene blend",
      "Features": "Compression, temperature",
      "Temperature Range": "Hot/cold therapy",
      "Size": "One size fits most",
      "Washable": "Yes",
      "Medical Grade": "Yes",
      "Use Case": "Pain relief, recovery",
    },
    score: { design: 3.9, performance: 4.0, battery: 0, value: 4.5, features: 4.0 },
  },

  // ─── ASSISTIVE & SPECIALTY WEARABLES ───────────────────────────────────────────
  {
    id: "orcam-myeye-pro",
    name: "OrCam MyEye 3 Pro Vision Assistant",
    brand: "OrCam",
    category: "assistive-tech",
    price: 3999,
    rating: 4.7,
    reviewCount: 234,
    badge: "editors-choice",
    image: "https://images.unsplash.com/photo-1576091160550-112173f7f869?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Orcam-MyEye-Pro-Vision-Assistant/dp/B0D2P6RF84?tag=weyoowte-20",
    shortDescription: "Advanced AI vision assistant for the visually impaired with reading and facial recognition.",
    pros: [
      "Life-changing for visually impaired",
      "Reads text aloud",
      "Facial recognition",
      "Product identification",
      "Language translation",
    ],
    cons: [
      "Very expensive",
      "Requires training",
      "Limited battery",
    ],
    specs: {
      "Features": "Reading, facial recognition, translation",
      "Battery Life": "Up to 2 hours",
      "Connectivity": "Wi-Fi, Bluetooth",
      "Camera": "AI-powered",
      "Languages": "Multiple",
      "Accessibility": "For visually impaired",
      "Warranty": "2 years",
    },
    score: { design: 4.6, performance: 4.7, battery: 3.5, value: 3.8, features: 4.8 },
    featured: true,
  },
  {
    id: "language-translator-device",
    name: "AI Language Translator Device",
    brand: "Generic",
    category: "assistive-tech",
    price: 149,
    rating: 4.2,
    reviewCount: 567,
    badge: "new",
    image: "https://images.unsplash.com/photo-1576091160550-112173f7f869?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/Language-Translator-Devices/s?k=Language+Translator+Devices?tag=weyoowte-20",
    shortDescription: "Portable AI translator supporting 150 languages with offline translation capability.",
    pros: [
      "150 languages",
      "Offline translation",
      "Real-time translation",
      "Affordable",
      "Compact design",
    ],
    cons: [
      "Accuracy varies",
      "Limited battery",
      "Small screen",
    ],
    specs: {
      "Languages": "150 supported",
      "Features": "Offline, real-time translation",
      "Battery Life": "Up to 10 hours",
      "Connectivity": "Wi-Fi, Bluetooth",
      "Recording": "Voice recording",
      "Photo Translation": "Yes",
      "Size": "Pocket-sized",
    },
    score: { design: 4.1, performance: 4.2, battery: 4.3, value: 4.4, features: 4.3 },
  },
  {
    id: "gripbeats-music-device",
    name: "GripBeats Wearable Music Device",
    brand: "GripBeats",
    category: "assistive-tech",
    price: 199,
    rating: 4.3,
    reviewCount: 345,
    image: "https://images.unsplash.com/photo-1576091160550-112173f7f869?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/GripBeats-Wearable-Music-Device/s?k=gripbeats?tag=weyoowte-20",
    shortDescription: "Innovative wearable device for creating music through movement and touch.",
    pros: [
      "Create music with movement",
      "Wireless Bluetooth",
      "Multiple instruments",
      "Fun and creative",
      "Accessible",
    ],
    cons: [
      "Limited battery",
      "Steep learning curve",
      "Niche use case",
    ],
    specs: {
      "Features": "Music creation, movement",
      "Connectivity": "Bluetooth",
      "Battery Life": "Up to 8 hours",
      "Instruments": "Multiple styles",
      "Compatibility": "iOS, Android, Mac, Windows",
      "Use Case": "Music creation, therapy",
      "Warranty": "1 year",
    },
    score: { design: 4.3, performance: 4.2, battery: 4.1, value: 4.1, features: 4.4 },
  },
  {
    id: "alivecor-kardia",
    name: "AliveCor KardiaMobile ECG Monitor",
    brand: "AliveCor",
    category: "assistive-tech",
    price: 129,
    rating: 4.4,
    reviewCount: 678,
    badge: "editors-choice",
    image: "https://images.unsplash.com/photo-1576091160550-112173f7f869?w=600&q=80",
    amazonUrl: "https://www.amazon.ca/AliveCor-KardiaMobile-ECG-Monitor/s?k=alivecor?tag=weyoowte-20",
    shortDescription: "Portable ECG monitor for detecting AFib and heart conditions in 30 seconds.",
    pros: [
      "Medical-grade ECG",
      "Detect AFib",
      "30-second readings",
      "Portable design",
      "FDA approved",
    ],
    cons: [
      "Requires smartphone",
      "Subscription for full features",
      "Limited battery",
    ],
    specs: {
      "Features": "ECG, AFib detection",
      "Reading Time": "30 seconds",
      "Connectivity": "Bluetooth",
      "Battery Life": "Up to 30 days",
      "Compatibility": "iOS, Android",
      "Medical Grade": "FDA approved",
      "Warranty": "2 years",
    },
    score: { design: 4.3, performance: 4.4, battery: 4.5, value: 4.2, features: 4.5 },
  },
];


// ─── HELPER FUNCTIONS ───────────────────────────────────────────
export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.category === categoryId);
}

export function getCategoryById(id: string): Category | undefined {
  return categories.find((c) => c.id === id);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured).slice(0, 6);
}

export function getTopRatedProducts(limit: number = 5): Product[] {
  return [...products].sort((a, b) => b.rating - a.rating).slice(0, limit);
}
