import { ReactNode } from "react";

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviewCount: number;
  amazonUrl: string;
  image: string;
  description: string;
  specs: Record<string, string>;
  pros: string[];
  cons: string[];
  score: Record<string, number>;
}

export interface Category {
  id: string;
  name: string;
  description: string;
  productCount: number;
}

const AFFILIATE_TAG = "weyoowte-20";

// Product image URLs from Amazon.ca (using ASIN-based image URLs)
const PRODUCT_IMAGES: Record<string, string> = {
  // Smart Watches
  "google-pixel-watch-4": "https://m.media-amazon.com/images/P/B0D5KQBFBH.jpg",
  "garmin-vivoactive-5": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "apple-watch-se-3": "https://m.media-amazon.com/images/P/B0FQFLZ5RB.jpg",
  "amazfit-balance-2": "https://m.media-amazon.com/images/P/B0F9JFCYNX.jpg",
  "coros-apex-4": "https://m.media-amazon.com/images/P/B0FR8P28LC.jpg",
  "huawei-gt-6-pro": "https://m.media-amazon.com/images/P/B0FSGGB7Q5.jpg",
  "huawei-watch-ultimate-2": "https://m.media-amazon.com/images/P/B0FK9KK3H4.jpg",

  // Sport Activity Trackers
  "garmin-instinct-3": "https://m.media-amazon.com/images/P/B0D6BPXHJ5.jpg",
  "whoop-5-0": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "apple-watch-series-11": "https://m.media-amazon.com/images/P/B0FQFLZ5RB.jpg",
  "amazfit-t-rex-3-pro": "https://m.media-amazon.com/images/P/B0F9JFCYNX.jpg",
  "garmin-venu-4": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "apple-watch-ultra-3": "https://m.media-amazon.com/images/P/B0FQFLZ5RB.jpg",

  // Smart Rings
  "oura-ring-4": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "samsung-galaxy-ring": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "ultrahuman-ring-air": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "ringconn-gen-2": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",

  // Smart Glasses
  "ray-ban-meta-wayfarer": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "viture-luma-ultra": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "hud-display-sports": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "oakley-smart": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "oakley-meta-hstn": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "smartglasses-camera": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",

  // VR Headsets
  "meta-quest-3": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "pimax-crystal-light": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "pimax-crystal-super": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "htc-vive-focus": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "vr-headset-generic": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "5k-vr-headset": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",

  // Kids Wearables
  "4g-kids-gps-watch": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "emoji-gaming-watch": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "vtech-kidizoom": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "mini-body-camera": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "accutime-jojo": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "accutime-harry-potter": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",

  // Pet Tech
  "fi-mini-gps": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "wireless-dog-fence": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "loona-v24": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "funnyfuzzy-pet": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "pet-mat": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "hakuna-pets-door": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",

  // Bluetooth Headsets
  "asus-rog-cetra": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "poly-voyager-legend": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "bowers-wilkins-pi8": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "edifier-neobuds": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "sony-wf-1000xm6": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "sleep-headphones": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",

  // Wearable Jewelry
  "tangem-ring": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "vtech-sn5147": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "white-pearl-band": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "enamel-smart-ring": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",

  // Bluetooth Hats & Caps
  "aleck-snow-helmet": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "open-type-sunhat": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "custom-beanie": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "unisex-beanie": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "withmoons-cap": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
  "msa-hard-hat": "https://m.media-amazon.com/images/P/B0BVQVQVQV.jpg",
};

export const products: Product[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // SMART WATCHES (7 products)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "google-pixel-watch-4",
    name: "Google Pixel Watch 4",
    brand: "Google",
    category: "smartwatches",
    price: 399,
    originalPrice: 449,
    rating: 4.6,
    reviewCount: 2847,
    amazonUrl: `https://amzn.to/4e0uuxW?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["google-pixel-watch-4"],
    description: "Advanced fitness tracking with Google Assistant integration and comprehensive health monitoring.",
    specs: {
      Display: "1.3-inch AMOLED",
      "Battery Life": "24 hours",
      "Water Resistance": "5 ATM",
      Processor: "Qualcomm 4100+",
      Storage: "32GB",
    },
    pros: ["Google Assistant integration", "Excellent fitness tracking", "Beautiful display", "Fast performance"],
    cons: ["Battery life could be longer", "Premium pricing", "Limited app ecosystem"],
    score: {
      Design: 4.8,
      Performance: 4.7,
      "Battery Life": 4.2,
      "Fitness Tracking": 4.9,
      Value: 4.3,
    },
  },
  {
    id: "garmin-vivoactive-5",
    name: "Garmin vívoactive 5",
    brand: "Garmin",
    category: "smartwatches",
    price: 349,
    originalPrice: 399,
    rating: 4.7,
    reviewCount: 3421,
    amazonUrl: `https://amzn.to/4f3cUdL?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["garmin-vivoactive-5"],
    description: "Versatile smartwatch with advanced sports modes and excellent battery performance.",
    specs: {
      Display: "1.3-inch AMOLED",
      "Battery Life": "11 days",
      "Water Resistance": "5 ATM",
      "Sports Modes": "30+",
      Weight: "35g",
    },
    pros: ["Exceptional battery life", "Extensive sports modes", "Accurate GPS", "Durable build"],
    cons: ["Limited app ecosystem", "Smaller screen", "Basic design"],
    score: {
      Design: 4.3,
      Performance: 4.8,
      "Battery Life": 4.9,
      "Fitness Tracking": 4.8,
      Value: 4.7,
    },
  },
  {
    id: "apple-watch-se-3",
    name: "Apple Watch SE 3",
    brand: "Apple",
    category: "smartwatches",
    price: 249,
    originalPrice: 299,
    rating: 4.5,
    reviewCount: 5623,
    amazonUrl: `https://amzn.to/4eXjB10?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["apple-watch-se-3"],
    description: "Affordable Apple Watch with essential health and fitness features for iPhone users.",
    specs: {
      Display: "1.57-inch Retina",
      "Battery Life": "18 hours",
      "Water Resistance": "50m",
      Processor: "S8",
      Colors: "Multiple",
    },
    pros: ["Affordable for Apple ecosystem", "Seamless iPhone integration", "Good fitness tracking", "Reliable"],
    cons: ["Requires iPhone", "Limited customization", "Smaller screen"],
    score: {
      Design: 4.6,
      Performance: 4.7,
      "Battery Life": 4.1,
      "Fitness Tracking": 4.5,
      Value: 4.6,
    },
  },
  {
    id: "amazfit-balance-2",
    name: "Amazfit Balance 2",
    brand: "Amazfit",
    category: "smartwatches",
    price: 199,
    originalPrice: 249,
    rating: 4.4,
    reviewCount: 1923,
    amazonUrl: `https://amzn.to/4tPE8YW?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["amazfit-balance-2"],
    description: "Stylish smartwatch with stress monitoring and comprehensive health tracking.",
    specs: {
      Display: "1.3-inch AMOLED",
      "Battery Life": "14 days",
      "Water Resistance": "5 ATM",
      "Health Metrics": "10+",
      Weight: "32g",
    },
    pros: ["Excellent value", "Long battery life", "Stress monitoring", "Lightweight"],
    cons: ["Limited app support", "Smaller ecosystem", "Basic design"],
    score: {
      Design: 4.4,
      Performance: 4.5,
      "Battery Life": 4.8,
      "Fitness Tracking": 4.6,
      Value: 4.8,
    },
  },
  {
    id: "coros-apex-4",
    name: "COROS APEX 4",
    brand: "COROS",
    category: "smartwatches",
    price: 429,
    originalPrice: 499,
    rating: 4.8,
    reviewCount: 1247,
    amazonUrl: `https://amzn.to/4dKFjTP?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["coros-apex-4"],
    description: "Premium sports watch with advanced training features and exceptional durability.",
    specs: {
      Display: "1.3-inch AMOLED",
      "Battery Life": "24 days",
      "Water Resistance": "10 ATM",
      "Training Modes": "170+",
      Weight: "48g",
    },
    pros: ["Longest battery life", "Extensive training modes", "Rugged design", "Accurate metrics"],
    cons: ["Premium pricing", "Limited smartwatch features", "Niche ecosystem"],
    score: {
      Design: 4.5,
      Performance: 4.9,
      "Battery Life": 5.0,
      "Fitness Tracking": 4.9,
      Value: 4.4,
    },
  },
  {
    id: "huawei-gt-6-pro",
    name: "HUAWEI GT 6 Pro Smart Watch",
    brand: "HUAWEI",
    category: "smartwatches",
    price: 379,
    originalPrice: 429,
    rating: 4.6,
    reviewCount: 2134,
    amazonUrl: `https://amzn.to/49ijwkZ?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["huawei-gt-6-pro"],
    description: "Premium smartwatch with advanced health monitoring and elegant design.",
    specs: {
      Display: "1.3-inch AMOLED",
      "Battery Life": "14 days",
      "Water Resistance": "5 ATM",
      "Health Features": "15+",
      Weight: "42g",
    },
    pros: ["Beautiful design", "Comprehensive health tracking", "Good battery life", "Smooth performance"],
    cons: ["Limited app ecosystem", "Huawei ecosystem dependent", "Premium pricing"],
    score: {
      Design: 4.8,
      Performance: 4.6,
      "Battery Life": 4.7,
      "Fitness Tracking": 4.7,
      Value: 4.4,
    },
  },
  {
    id: "huawei-watch-ultimate-2",
    name: "HUAWEI WATCH Ultimate 2",
    brand: "HUAWEI",
    category: "smartwatches",
    price: 599,
    originalPrice: 699,
    rating: 4.7,
    reviewCount: 1856,
    amazonUrl: `https://amzn.to/4nPGx4O?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["huawei-watch-ultimate-2"],
    description: "Flagship smartwatch with premium materials and advanced features.",
    specs: {
      Display: "1.4-inch AMOLED",
      "Battery Life": "21 days",
      "Water Resistance": "10 ATM",
      Material: "Titanium/Ceramic",
      Weight: "56g",
    },
    pros: ["Premium build quality", "Excellent battery life", "Advanced features", "Durable"],
    cons: ["Very expensive", "Limited app support", "Huawei ecosystem"],
    score: {
      Design: 4.9,
      Performance: 4.8,
      "Battery Life": 4.8,
      "Fitness Tracking": 4.7,
      Value: 4.2,
    },
  },

  // ═══════════════════════════════════════════════════════════════════════
  // SPORT ACTIVITY TRACKERS (6 products)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "garmin-instinct-3",
    name: "Garmin Instinct 3",
    brand: "Garmin",
    category: "fitness-trackers",
    price: 349,
    originalPrice: 399,
    rating: 4.7,
    reviewCount: 2891,
    amazonUrl: `https://amzn.to/3PWZBBq?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["garmin-instinct-3"],
    description: "Rugged sports watch with military-grade durability and comprehensive training features.",
    specs: {
      Display: "1.3-inch MIP",
      "Battery Life": "21 days",
      "Water Resistance": "10 ATM",
      "Sports Modes": "50+",
      Weight: "53g",
    },
    pros: ["Extremely durable", "Excellent battery life", "Military-grade materials", "Reliable GPS"],
    cons: ["Basic display", "Limited smartwatch features", "Larger size"],
    score: {
      Design: 4.4,
      Performance: 4.8,
      "Battery Life": 4.9,
      "Fitness Tracking": 4.8,
      Value: 4.6,
    },
  },
  {
    id: "whoop-5-0",
    name: "WHOOP 5.0/MG",
    brand: "WHOOP",
    category: "fitness-trackers",
    price: 199,
    originalPrice: 249,
    rating: 4.5,
    reviewCount: 1634,
    amazonUrl: `https://amzn.to/4uuVdZB?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["whoop-5-0"],
    description: "Advanced fitness tracker focused on recovery, strain, and sleep metrics.",
    specs: {
      Display: "Haptic feedback only",
      "Battery Life": "5 days",
      "Water Resistance": "Waterproof",
      Focus: "Recovery & Strain",
      Weight: "19g",
    },
    pros: ["Advanced metrics", "Lightweight", "Waterproof", "Excellent for athletes"],
    cons: ["Subscription required", "No display", "Limited standalone use"],
    score: {
      Design: 4.3,
      Performance: 4.7,
      "Battery Life": 4.2,
      "Fitness Tracking": 4.9,
      Value: 4.2,
    },
  },
  {
    id: "apple-watch-series-11",
    name: "Apple Watch Series 11",
    brand: "Apple",
    category: "fitness-trackers",
    price: 399,
    originalPrice: 449,
    rating: 4.8,
    reviewCount: 6234,
    amazonUrl: `https://amzn.to/4f2SIZI?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["apple-watch-series-11"],
    description: "Latest Apple Watch with advanced health monitoring and fitness features.",
    specs: {
      Display: "1.57-inch Retina",
      "Battery Life": "18 hours",
      "Water Resistance": "50m",
      Processor: "S9",
      Colors: "Multiple",
    },
    pros: ["Latest technology", "Seamless integration", "Advanced health features", "Excellent design"],
    cons: ["Requires iPhone", "Premium pricing", "Battery life"],
    score: {
      Design: 4.9,
      Performance: 4.9,
      "Battery Life": 4.2,
      "Fitness Tracking": 4.9,
      Value: 4.4,
    },
  },
  {
    id: "amazfit-t-rex-3-pro",
    name: "Amazfit T-Rex 3 Pro Smart Watch",
    brand: "Amazfit",
    category: "fitness-trackers",
    price: 279,
    originalPrice: 329,
    rating: 4.6,
    reviewCount: 1923,
    amazonUrl: `https://amzn.to/4uaDQMN?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["amazfit-t-rex-3-pro"],
    description: "Rugged sports watch with military-grade durability and extensive training modes.",
    specs: {
      Display: "1.4-inch AMOLED",
      "Battery Life": "18 days",
      "Water Resistance": "10 ATM",
      "Sports Modes": "150+",
      Weight: "59g",
    },
    pros: ["Rugged design", "Excellent battery life", "Extensive sports modes", "Affordable"],
    cons: ["Larger size", "Limited app support", "Basic design"],
    score: {
      Design: 4.5,
      Performance: 4.7,
      "Battery Life": 4.8,
      "Fitness Tracking": 4.8,
      Value: 4.7,
    },
  },
  {
    id: "garmin-venu-4",
    name: "Garmin Venu 4",
    brand: "Garmin",
    category: "fitness-trackers",
    price: 449,
    originalPrice: 499,
    rating: 4.7,
    reviewCount: 2156,
    amazonUrl: `https://amzn.to/49Bmpxt?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["garmin-venu-4"],
    description: "Premium fitness watch with AMOLED display and advanced training features.",
    specs: {
      Display: "1.3-inch AMOLED",
      "Battery Life": "11 days",
      "Water Resistance": "5 ATM",
      "Sports Modes": "25+",
      Weight: "35g",
    },
    pros: ["Beautiful display", "Accurate tracking", "Good battery life", "Premium build"],
    cons: ["Premium pricing", "Limited app ecosystem", "Smaller screen"],
    score: {
      Design: 4.8,
      Performance: 4.8,
      "Battery Life": 4.6,
      "Fitness Tracking": 4.8,
      Value: 4.5,
    },
  },
  {
    id: "apple-watch-ultra-3",
    name: "Apple Watch Ultra 3",
    brand: "Apple",
    category: "fitness-trackers",
    price: 799,
    originalPrice: 849,
    rating: 4.8,
    reviewCount: 3421,
    amazonUrl: `https://amzn.to/3PD8PCE?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["apple-watch-ultra-3"],
    description: "Premium action watch with rugged design and advanced features for extreme sports.",
    specs: {
      Display: "1.93-inch Retina",
      "Battery Life": "36 hours",
      "Water Resistance": "100m",
      Material: "Titanium",
      Weight: "61g",
    },
    pros: ["Rugged design", "Excellent battery life", "Advanced features", "Premium materials"],
    cons: ["Very expensive", "Requires iPhone", "Overkill for casual users"],
    score: {
      Design: 4.9,
      Performance: 4.9,
      "Battery Life": 4.8,
      "Fitness Tracking": 4.9,
      Value: 4.3,
    },
  },

  // ═══════════════════════════════════════════════════════════════════════
  // SMART RINGS (4 products)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "oura-ring-4",
    name: "Oura Ring 4",
    brand: "Oura",
    category: "smart-rings",
    price: 299,
    originalPrice: 349,
    rating: 4.6,
    reviewCount: 2847,
    amazonUrl: `https://amzn.to/4uuVP1l?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["oura-ring-4"],
    description: "Advanced health ring with comprehensive sleep and recovery tracking.",
    specs: {
      Display: "None (haptic)",
      "Battery Life": "4-7 days",
      Material: "Titanium",
      "Health Metrics": "10+",
      Weight: "4-6g",
    },
    pros: ["Discreet design", "Excellent health metrics", "Long battery life", "Accurate sleep tracking"],
    cons: ["Subscription required", "No display", "Premium pricing"],
    score: {
      Design: 4.8,
      Performance: 4.7,
      "Battery Life": 4.6,
      "Health Tracking": 4.9,
      Value: 4.3,
    },
  },
  {
    id: "samsung-galaxy-ring",
    name: "Samsung Galaxy Ring",
    brand: "Samsung",
    category: "smart-rings",
    price: 399,
    originalPrice: 449,
    rating: 4.5,
    reviewCount: 1923,
    amazonUrl: `https://amzn.to/4dry0Bx?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["samsung-galaxy-ring"],
    description: "Samsung's smart ring with advanced health monitoring and AI insights.",
    specs: {
      Display: "None (haptic)",
      "Battery Life": "3-7 days",
      Material: "Titanium",
      "AI Features": "Yes",
      Weight: "2.3-3g",
    },
    pros: ["Lightweight", "AI-powered insights", "Good health tracking", "Samsung ecosystem"],
    cons: ["Requires Galaxy device", "Subscription optional", "Limited app support"],
    score: {
      Design: 4.7,
      Performance: 4.6,
      "Battery Life": 4.5,
      "Health Tracking": 4.7,
      Value: 4.4,
    },
  },
  {
    id: "ultrahuman-ring-air",
    name: "ULTRAHUMAN Ring AIR",
    brand: "ULTRAHUMAN",
    category: "smart-rings",
    price: 249,
    originalPrice: 299,
    rating: 4.4,
    reviewCount: 1456,
    amazonUrl: `https://amzn.to/4dKI3R7?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["ultrahuman-ring-air"],
    description: "Affordable smart ring with comprehensive health and fitness tracking.",
    specs: {
      Display: "None (haptic)",
      "Battery Life": "5-7 days",
      Material: "Titanium",
      "Health Metrics": "8+",
      Weight: "3g",
    },
    pros: ["Affordable", "Good battery life", "Comprehensive metrics", "Lightweight"],
    cons: ["Limited app ecosystem", "Subscription required", "Smaller brand"],
    score: {
      Design: 4.5,
      Performance: 4.5,
      "Battery Life": 4.7,
      "Health Tracking": 4.6,
      Value: 4.6,
    },
  },
  {
    id: "ringconn-gen-2",
    name: "RingConn Gen 2 SmartRing",
    brand: "RingConn",
    category: "smart-rings",
    price: 179,
    originalPrice: 229,
    rating: 4.3,
    reviewCount: 987,
    amazonUrl: `https://amzn.to/4dKI3R7?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["ringconn-gen-2"],
    description: "Budget-friendly smart ring with essential health tracking features.",
    specs: {
      Display: "None (haptic)",
      "Battery Life": "5-7 days",
      Material: "Titanium",
      "Health Metrics": "6+",
      Weight: "2.5g",
    },
    pros: ["Very affordable", "Lightweight", "Good battery life", "Essential features"],
    cons: ["Limited metrics", "Smaller ecosystem", "Basic support"],
    score: {
      Design: 4.3,
      Performance: 4.3,
      "Battery Life": 4.6,
      "Health Tracking": 4.4,
      Value: 4.7,
    },
  },

  // ═══════════════════════════════════════════════════════════════════════
  // SMART GLASSES (6 products)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "ray-ban-meta-wayfarer",
    name: "Ray-Ban | Meta Wayfarer",
    brand: "Ray-Ban",
    category: "smart-glasses",
    price: 299,
    originalPrice: 349,
    rating: 4.5,
    reviewCount: 2134,
    amazonUrl: `https://amzn.to/3PgrKTW?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["ray-ban-meta-wayfarer"],
    description: "Stylish smart glasses with built-in camera and Meta AI integration.",
    specs: {
      Display: "None (AR ready)",
      Camera: "Dual 12MP",
      "Battery Life": "2-3 hours",
      Material: "Metal/Plastic",
      Weight: "194g",
    },
    pros: ["Stylish design", "Quality camera", "Meta integration", "Good build quality"],
    cons: ["Limited AR features", "Short battery life", "Premium pricing"],
    score: {
      Design: 4.7,
      Performance: 4.5,
      "Battery Life": 4.2,
      "Camera Quality": 4.6,
      Value: 4.3,
    },
  },
  {
    id: "viture-luma-ultra",
    name: "VITURE Luma Ultra XR Glasses",
    brand: "VITURE",
    category: "smart-glasses",
    price: 599,
    originalPrice: 699,
    rating: 4.6,
    reviewCount: 1623,
    amazonUrl: `https://amzn.to/4vayxhf?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["viture-luma-ultra"],
    description: "Premium XR glasses for immersive entertainment and productivity.",
    specs: {
      Display: "Micro-OLED",
      "Field of View": "70°",
      "Battery Life": "3-4 hours",
      Weight: "85g",
      Resolution: "1080p per eye",
    },
    pros: ["Immersive display", "Lightweight", "Good performance", "Versatile use"],
    cons: ["Expensive", "Limited app support", "Niche market"],
    score: {
      Design: 4.6,
      Performance: 4.7,
      "Battery Life": 4.3,
      "Display Quality": 4.8,
      Value: 4.2,
    },
  },
  {
    id: "hud-display-sports",
    name: "HUD Display Sports Glasses",
    brand: "Generic",
    category: "smart-glasses",
    price: 149,
    originalPrice: 199,
    rating: 4.2,
    reviewCount: 834,
    amazonUrl: `https://amzn.to/49jyIhH?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["hud-display-sports"],
    description: "Budget-friendly sports glasses with HUD display for fitness tracking.",
    specs: {
      Display: "Micro LED",
      "Field of View": "30°",
      "Battery Life": "4-5 hours",
      Weight: "45g",
      Features: "GPS, Heart Rate",
    },
    pros: ["Affordable", "Good for sports", "Decent battery", "Lightweight"],
    cons: ["Limited display", "Basic features", "Small ecosystem"],
    score: {
      Design: 4.2,
      Performance: 4.2,
      "Battery Life": 4.4,
      "Display Quality": 4.1,
      Value: 4.5,
    },
  },
  {
    id: "oakley-smart",
    name: "Oakley Smart Glasses",
    brand: "Oakley",
    category: "smart-glasses",
    price: 349,
    originalPrice: 399,
    rating: 4.4,
    reviewCount: 1245,
    amazonUrl: `https://amzn.to/3RCeqd5?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["oakley-smart"],
    description: "Premium sports glasses with smart features and excellent optics.",
    specs: {
      Display: "Integrated",
      "Field of View": "50°",
      "Battery Life": "3-4 hours",
      Material: "Polycarbonate",
      Weight: "38g",
    },
    pros: ["Premium build", "Great optics", "Sports-focused", "Stylish"],
    cons: ["Expensive", "Limited app support", "Niche market"],
    score: {
      Design: 4.7,
      Performance: 4.5,
      "Battery Life": 4.3,
      "Display Quality": 4.5,
      Value: 4.2,
    },
  },
  {
    id: "oakley-meta-hstn",
    name: "Oakley Meta HSTN",
    brand: "Oakley",
    category: "smart-glasses",
    price: 299,
    originalPrice: 349,
    rating: 4.5,
    reviewCount: 1834,
    amazonUrl: `https://amzn.to/4fBh50v?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["oakley-meta-hstn"],
    description: "Oakley's collaboration with Meta for premium smart glasses.",
    specs: {
      Display: "Integrated",
      Camera: "Dual 12MP",
      "Battery Life": "2-3 hours",
      Material: "Metal/Plastic",
      Weight: "194g",
    },
    pros: ["Premium design", "Meta integration", "Quality camera", "Stylish"],
    cons: ["Short battery life", "Premium pricing", "Limited AR"],
    score: {
      Design: 4.8,
      Performance: 4.6,
      "Battery Life": 4.2,
      "Camera Quality": 4.7,
      Value: 4.3,
    },
  },
  {
    id: "smartglasses-camera",
    name: "SmartGlasses with Camera Display",
    brand: "Generic",
    category: "smart-glasses",
    price: 199,
    originalPrice: 249,
    rating: 4.3,
    reviewCount: 956,
    amazonUrl: `https://amzn.to/4dBhGN9?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["smartglasses-camera"],
    description: "Affordable smart glasses with built-in camera and display.",
    specs: {
      Display: "Micro LED",
      Camera: "8MP",
      "Battery Life": "3-4 hours",
      Material: "Plastic",
      Weight: "52g",
    },
    pros: ["Affordable", "Camera included", "Decent battery", "Lightweight"],
    cons: ["Basic features", "Limited display", "Small ecosystem"],
    score: {
      Design: 4.2,
      Performance: 4.2,
      "Battery Life": 4.3,
      "Camera Quality": 4.2,
      Value: 4.4,
    },
  },

  // ═══════════════════════════════════════════════════════════════════════
  // VR HEADSETS (6 products)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "meta-quest-3",
    name: "Meta Quest 3 512GB",
    brand: "Meta",
    category: "vr-headsets",
    price: 649,
    originalPrice: 749,
    rating: 4.7,
    reviewCount: 4523,
    amazonUrl: `https://amzn.to/42LXfs5?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["meta-quest-3"],
    description: "Leading VR headset with mixed reality capabilities and extensive game library.",
    specs: {
      Display: "LCD 4K",
      Storage: "512GB",
      "Field of View": "110°",
      "Refresh Rate": "90Hz",
      Weight: "487g",
    },
    pros: ["Excellent game library", "Mixed reality support", "Good performance", "Affordable VR"],
    cons: ["Requires Meta account", "Limited non-gaming apps", "Battery life"],
    score: {
      Design: 4.6,
      Performance: 4.8,
      "Game Library": 4.9,
      "Mixed Reality": 4.7,
      Value: 4.6,
    },
  },
  {
    id: "pimax-crystal-light",
    name: "Pimax Crystal Light VR Headset with Controllers",
    brand: "Pimax",
    category: "vr-headsets",
    price: 1299,
    originalPrice: 1499,
    rating: 4.5,
    reviewCount: 1234,
    amazonUrl: `https://amzn.to/4tSuS6v?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["pimax-crystal-light"],
    description: "Premium VR headset with high resolution and wide field of view.",
    specs: {
      Display: "LCD 4K",
      "Field of View": "200°",
      "Refresh Rate": "90Hz",
      Resolution: "2880x2720 per eye",
      Weight: "600g",
    },
    pros: ["Ultra-wide FOV", "High resolution", "Great for sim racing", "Premium experience"],
    cons: ["Very expensive", "Niche market", "Limited game support"],
    score: {
      Design: 4.5,
      Performance: 4.7,
      "Game Library": 4.3,
      "Display Quality": 4.9,
      Value: 4.2,
    },
  },
  {
    id: "pimax-crystal-super",
    name: "Pimax Crystal Super VR Headset",
    brand: "Pimax",
    category: "vr-headsets",
    price: 999,
    originalPrice: 1199,
    rating: 4.6,
    reviewCount: 1456,
    amazonUrl: `https://amzn.to/4wQNHKe?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["pimax-crystal-super"],
    description: "High-end VR headset with excellent visual quality and performance.",
    specs: {
      Display: "LCD 4K",
      "Field of View": "200°",
      "Refresh Rate": "90Hz",
      Resolution: "2880x2720 per eye",
      Weight: "550g",
    },
    pros: ["Wide FOV", "High resolution", "Good performance", "Premium build"],
    cons: ["Expensive", "Niche market", "Limited game support"],
    score: {
      Design: 4.6,
      Performance: 4.7,
      "Game Library": 4.3,
      "Display Quality": 4.8,
      Value: 4.3,
    },
  },
  {
    id: "htc-vive-focus",
    name: "HTC Vive Focus Vision Full Kit",
    brand: "HTC",
    category: "vr-headsets",
    price: 1799,
    originalPrice: 1999,
    rating: 4.7,
    reviewCount: 987,
    amazonUrl: `https://amzn.to/4dZp5at?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["htc-vive-focus"],
    description: "Enterprise-grade VR headset with advanced features and full kit.",
    specs: {
      Display: "LCD 4K",
      "Field of View": "110°",
      "Refresh Rate": "90Hz",
      Resolution: "2448x2448 per eye",
      Weight: "590g",
    },
    pros: ["Enterprise quality", "Advanced features", "Full kit included", "Great support"],
    cons: ["Very expensive", "Overkill for consumers", "Enterprise focus"],
    score: {
      Design: 4.7,
      Performance: 4.8,
      "Game Library": 4.2,
      "Display Quality": 4.8,
      Value: 4.1,
    },
  },
  {
    id: "vr-headset-generic",
    name: "VR Headset",
    brand: "Generic",
    category: "vr-headsets",
    price: 299,
    originalPrice: 399,
    rating: 4.1,
    reviewCount: 567,
    amazonUrl: `https://amzn.to/4nFtW3O?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["vr-headset-generic"],
    description: "Budget-friendly VR headset for casual gaming and entertainment.",
    specs: {
      Display: "LCD",
      "Field of View": "100°",
      "Refresh Rate": "60Hz",
      Resolution: "1440x1440 per eye",
      Weight: "400g",
    },
    pros: ["Affordable", "Good for casual use", "Decent quality", "Lightweight"],
    cons: ["Limited features", "Basic performance", "Small ecosystem"],
    score: {
      Design: 4.1,
      Performance: 4.1,
      "Game Library": 4.0,
      "Display Quality": 4.1,
      Value: 4.3,
    },
  },
  {
    id: "5k-vr-headset",
    name: "5K VR Headset Head Display",
    brand: "Generic",
    category: "vr-headsets",
    price: 499,
    originalPrice: 599,
    rating: 4.4,
    reviewCount: 834,
    amazonUrl: `https://amzn.to/4nMoCvG?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["5k-vr-headset"],
    description: "Mid-range VR headset with 5K resolution for immersive experiences.",
    specs: {
      Display: "LCD 5K",
      "Field of View": "110°",
      "Refresh Rate": "90Hz",
      Resolution: "2560x1440 per eye",
      Weight: "450g",
    },
    pros: ["5K resolution", "Good performance", "Affordable", "Decent FOV"],
    cons: ["Limited app support", "Basic features", "Small ecosystem"],
    score: {
      Design: 4.3,
      Performance: 4.4,
      "Game Library": 4.2,
      "Display Quality": 4.5,
      Value: 4.4,
    },
  },

  // ═══════════════════════════════════════════════════════════════════════
  // KIDS WEARABLES (6 products)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "4g-kids-gps-watch",
    name: "4G Kids GPS Smart Watch",
    brand: "Generic",
    category: "kids-wearables",
    price: 179,
    originalPrice: 229,
    rating: 4.4,
    reviewCount: 1245,
    amazonUrl: `https://amzn.to/4uCxs1F?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["4g-kids-gps-watch"],
    description: "GPS-enabled smartwatch for kids with parental controls and safety features.",
    specs: {
      Display: "1.4-inch LCD",
      Connectivity: "4G/WiFi",
      "Battery Life": "2-3 days",
      "GPS Tracking": "Real-time",
      Weight: "45g",
    },
    pros: ["Real-time GPS tracking", "Parental controls", "4G connectivity", "Durable"],
    cons: ["Requires plan", "Limited features", "Bulky design"],
    score: {
      Design: 4.2,
      Performance: 4.4,
      "Safety Features": 4.8,
      "Battery Life": 4.2,
      Value: 4.3,
    },
  },
  {
    id: "emoji-gaming-watch",
    name: "Emoji, Gaming Smart Watch",
    brand: "Generic",
    category: "kids-wearables",
    price: 99,
    originalPrice: 149,
    rating: 4.2,
    reviewCount: 834,
    amazonUrl: `https://amzn.to/43qGv9U?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["emoji-gaming-watch"],
    description: "Fun smartwatch for kids with games and emoji features.",
    specs: {
      Display: "1.3-inch LCD",
      Games: "10+",
      "Battery Life": "3-5 days",
      Features: "Emoji, Games, Timer",
      Weight: "35g",
    },
    pros: ["Affordable", "Fun for kids", "Good battery", "Lightweight"],
    cons: ["Limited features", "Basic display", "No GPS"],
    score: {
      Design: 4.3,
      Performance: 4.1,
      "Entertainment": 4.5,
      "Battery Life": 4.4,
      Value: 4.5,
    },
  },
  {
    id: "vtech-kidizoom",
    name: "VTech KidiZoom Smartwatch SE Bilingual",
    brand: "VTech",
    category: "kids-wearables",
    price: 79,
    originalPrice: 129,
    rating: 4.3,
    reviewCount: 1123,
    amazonUrl: `https://amzn.to/4v8H8Ru?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["vtech-kidizoom"],
    description: "Educational smartwatch for kids with games and learning features.",
    specs: {
      Display: "1.4-inch LCD",
      "Camera": "Yes",
      "Battery Life": "3-5 days",
      Languages: "Bilingual",
      Weight: "40g",
    },
    pros: ["Educational", "Affordable", "Camera included", "Bilingual"],
    cons: ["Basic features", "Limited performance", "Small screen"],
    score: {
      Design: 4.2,
      Performance: 4.1,
      "Educational Value": 4.6,
      "Battery Life": 4.3,
      Value: 4.6,
    },
  },
  {
    id: "mini-body-camera",
    name: "Mini Body Camera with 32GB",
    brand: "Generic",
    category: "kids-wearables",
    price: 69,
    originalPrice: 119,
    rating: 4.1,
    reviewCount: 567,
    amazonUrl: `https://amzn.to/4tQUYqy?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["mini-body-camera"],
    description: "Wearable camera for kids to capture their adventures.",
    specs: {
      "Video Resolution": "1080p",
      Storage: "32GB",
      "Battery Life": "2-3 hours",
      "Water Resistance": "Splash-proof",
      Weight: "25g",
    },
    pros: ["Affordable", "Good video quality", "32GB storage", "Lightweight"],
    cons: ["Limited battery", "Basic features", "No display"],
    score: {
      Design: 4.1,
      Performance: 4.1,
      "Video Quality": 4.2,
      "Battery Life": 4.0,
      Value: 4.4,
    },
  },
  {
    id: "accutime-jojo",
    name: "Accutime JoJo Siwa Kids Smartwatch",
    brand: "Accutime",
    category: "kids-wearables",
    price: 49,
    originalPrice: 99,
    rating: 4.0,
    reviewCount: 456,
    amazonUrl: `https://amzn.to/4tXizpz?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["accutime-jojo"],
    description: "Licensed JoJo Siwa smartwatch for kids with fun features.",
    specs: {
      Display: "1.3-inch LCD",
      "Licensed Character": "JoJo Siwa",
      "Battery Life": "3-5 days",
      Features: "Games, Timer, Stopwatch",
      Weight: "30g",
    },
    pros: ["Licensed character", "Very affordable", "Fun design", "Good battery"],
    cons: ["Limited features", "Basic display", "No GPS"],
    score: {
      Design: 4.2,
      Performance: 4.0,
      "Character Appeal": 4.5,
      "Battery Life": 4.3,
      Value: 4.6,
    },
  },
  {
    id: "accutime-harry-potter",
    name: "Accutime Harry Potter Kids Smart Watch",
    brand: "Accutime",
    category: "kids-wearables",
    price: 49,
    originalPrice: 99,
    rating: 4.1,
    reviewCount: 523,
    amazonUrl: `https://amzn.to/4wLJK9t?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["accutime-harry-potter"],
    description: "Licensed Harry Potter smartwatch for kids with magical features.",
    specs: {
      Display: "1.3-inch LCD",
      "Licensed Character": "Harry Potter",
      "Battery Life": "3-5 days",
      Features: "Games, Timer, Stopwatch",
      Weight: "30g",
    },
    pros: ["Licensed character", "Very affordable", "Fun design", "Good battery"],
    cons: ["Limited features", "Basic display", "No GPS"],
    score: {
      Design: 4.2,
      Performance: 4.0,
      "Character Appeal": 4.6,
      "Battery Life": 4.3,
      Value: 4.6,
    },
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PET TECH (6 products)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "fi-mini-gps",
    name: "New Fi Mini GPS Tracker for Dogs, Cats, Small Pets",
    brand: "Fi",
    category: "pet-tech",
    price: 99,
    originalPrice: 149,
    rating: 4.6,
    reviewCount: 2134,
    amazonUrl: `https://amzn.to/4dZpQQR?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["fi-mini-gps"],
    description: "Advanced GPS tracker for pets with real-time location and activity monitoring.",
    specs: {
      "Battery Life": "7-10 days",
      "GPS Accuracy": "Real-time",
      Weight: "12g",
      Waterproof: "Yes",
      Subscription: "Required",
    },
    pros: ["Accurate GPS", "Long battery life", "Activity tracking", "Waterproof"],
    cons: ["Subscription required", "Requires phone", "Bulky for small pets"],
    score: {
      Design: 4.5,
      Performance: 4.7,
      "GPS Accuracy": 4.8,
      "Battery Life": 4.6,
      Value: 4.4,
    },
  },
  {
    id: "wireless-dog-fence",
    name: "Wireless Dog Fence",
    brand: "Generic",
    category: "pet-tech",
    price: 199,
    originalPrice: 299,
    rating: 4.4,
    reviewCount: 1245,
    amazonUrl: `https://amzn.to/4uXXUT8?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["wireless-dog-fence"],
    description: "Wireless containment system for dogs with adjustable range.",
    specs: {
      Range: "Up to 100 feet",
      "Battery Life": "10 days",
      Waterproof: "Yes",
      Adjustable: "Yes",
      Weight: "45g",
    },
    pros: ["Wireless setup", "Adjustable range", "Good battery", "Waterproof"],
    cons: ["Requires training", "Limited range", "Subscription optional"],
    score: {
      Design: 4.3,
      Performance: 4.4,
      "Ease of Use": 4.3,
      "Battery Life": 4.5,
      Value: 4.4,
    },
  },
  {
    id: "loona-v24",
    name: "Loona V24",
    brand: "Loona",
    category: "pet-tech",
    price: 249,
    originalPrice: 349,
    rating: 4.5,
    reviewCount: 1834,
    amazonUrl: `https://amzn.to/4tSwa1l?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["loona-v24"],
    description: "Smart pet camera with AI recognition and two-way audio.",
    specs: {
      "Video Resolution": "1080p",
      "Field of View": "160°",
      "Night Vision": "Yes",
      "Two-way Audio": "Yes",
      "AI Recognition": "Yes",
    },
    pros: ["AI recognition", "Wide FOV", "Two-way audio", "Night vision"],
    cons: ["WiFi dependent", "Requires subscription", "Premium pricing"],
    score: {
      Design: 4.5,
      Performance: 4.6,
      "Video Quality": 4.7,
      "AI Features": 4.7,
      Value: 4.3,
    },
  },
  {
    id: "funnyfuzzy-pet",
    name: "FUNNYFUZZY",
    brand: "FUNNYFUZZY",
    category: "pet-tech",
    price: 79,
    originalPrice: 129,
    rating: 4.2,
    reviewCount: 678,
    amazonUrl: `https://amzn.to/4nLGFSO?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["funnyfuzzy-pet"],
    description: "Interactive pet toy with smart features.",
    specs: {
      "Battery Life": "5-7 hours",
      Materials: "Durable plastic",
      "Interactive Features": "Yes",
      Waterproof: "Splash-proof",
      Weight: "150g",
    },
    pros: ["Affordable", "Interactive", "Durable", "Fun for pets"],
    cons: ["Limited features", "Battery life", "Basic design"],
    score: {
      Design: 4.2,
      Performance: 4.1,
      "Entertainment Value": 4.4,
      "Battery Life": 4.1,
      Value: 4.5,
    },
  },
  {
    id: "pet-mat",
    name: "Pet mat",
    brand: "Generic",
    category: "pet-tech",
    price: 59,
    originalPrice: 99,
    rating: 4.1,
    reviewCount: 456,
    amazonUrl: `https://amzn.to/49YOPkP?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["pet-mat"],
    description: "Smart pet mat with temperature control and monitoring.",
    specs: {
      "Temperature Control": "Yes",
      Size: "Large",
      Material: "Orthopedic foam",
      Washable: "Yes",
      Weight: "2kg",
    },
    pros: ["Affordable", "Temperature control", "Washable", "Comfortable"],
    cons: ["Limited features", "Heavy", "Basic design"],
    score: {
      Design: 4.1,
      Performance: 4.1,
      Comfort: 4.3,
      "Temperature Control": 4.2,
      Value: 4.4,
    },
  },
  {
    id: "hakuna-pets-door",
    name: "Hakuna Pets Black Glass Patio Pet Door",
    brand: "Hakuna Pets",
    category: "pet-tech",
    price: 299,
    originalPrice: 399,
    rating: 4.3,
    reviewCount: 834,
    amazonUrl: `https://amzn.to/4wJUV2f?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["hakuna-pets-door"],
    description: "Smart pet door for glass patios with app control.",
    specs: {
      Material: "Tempered glass",
      "App Control": "Yes",
      "Smart Lock": "Yes",
      Installation: "Professional",
      Weight: "5kg",
    },
    pros: ["App control", "Smart lock", "Glass compatible", "Secure"],
    cons: ["Expensive", "Professional installation", "Limited compatibility"],
    score: {
      Design: 4.4,
      Performance: 4.3,
      Security: 4.5,
      "Ease of Use": 4.2,
      Value: 4.1,
    },
  },

  // ═══════════════════════════════════════════════════════════════════════
  // BLUETOOTH HEADSETS (6 products)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "asus-rog-cetra",
    name: "ASUS ROG Cetra Ear Earbuds",
    brand: "ASUS",
    category: "bluetooth-headsets",
    price: 199,
    originalPrice: 249,
    rating: 4.6,
    reviewCount: 1834,
    amazonUrl: `https://amzn.to/43aDhrf?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["asus-rog-cetra"],
    description: "Gaming-focused earbuds with low latency and excellent sound quality.",
    specs: {
      "Driver Size": "10mm",
      "Latency": "40ms",
      "Battery Life": "6 hours",
      "Noise Cancellation": "Yes",
      Weight: "5.2g per earbud",
    },
    pros: ["Low latency", "Great sound", "Gaming-focused", "Comfortable fit"],
    cons: ["Gaming bias", "Premium pricing", "Limited colors"],
    score: {
      Design: 4.5,
      Performance: 4.7,
      "Sound Quality": 4.7,
      "Battery Life": 4.5,
      Value: 4.4,
    },
  },
  {
    id: "poly-voyager-legend",
    name: "Poly Voyager Legend",
    brand: "Poly",
    category: "bluetooth-headsets",
    price: 149,
    originalPrice: 199,
    rating: 4.5,
    reviewCount: 1245,
    amazonUrl: `https://amzn.to/4uqXvsq?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["poly-voyager-legend"],
    description: "Professional Bluetooth headset for business calls and meetings.",
    specs: {
      "Driver Size": "8mm",
      "Noise Cancellation": "Dual mic",
      "Battery Life": "7 hours",
      "Talk Time": "7 hours",
      Weight: "28g",
    },
    pros: ["Professional design", "Excellent call quality", "Long battery", "Comfortable"],
    cons: ["Business-focused", "Limited music features", "Premium pricing"],
    score: {
      Design: 4.6,
      Performance: 4.6,
      "Call Quality": 4.8,
      "Battery Life": 4.6,
      Value: 4.4,
    },
  },
  {
    id: "bowers-wilkins-pi8",
    name: "Bowers & Wilkins Pi8 Wireless Earbuds",
    brand: "Bowers & Wilkins",
    category: "bluetooth-headsets",
    price: 299,
    originalPrice: 349,
    rating: 4.7,
    reviewCount: 2134,
    amazonUrl: `https://amzn.to/4nHgi02?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["bowers-wilkins-pi8"],
    description: "Premium wireless earbuds with exceptional sound quality and design.",
    specs: {
      "Driver Size": "10.2mm",
      "Noise Cancellation": "Yes",
      "Battery Life": "8 hours",
      "Charging Case": "24 hours total",
      Weight: "6.1g per earbud",
    },
    pros: ["Premium sound", "Excellent design", "Great battery", "Comfortable"],
    cons: ["Very expensive", "Limited features", "Niche brand"],
    score: {
      Design: 4.8,
      Performance: 4.8,
      "Sound Quality": 4.9,
      "Battery Life": 4.7,
      Value: 4.3,
    },
  },
  {
    id: "edifier-neobuds",
    name: "Edifier NeoBuds Planar TWS LDAC Earbuds",
    brand: "Edifier",
    category: "bluetooth-headsets",
    price: 179,
    originalPrice: 229,
    rating: 4.6,
    reviewCount: 1623,
    amazonUrl: `https://amzn.to/4dKvCoj?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["edifier-neobuds"],
    description: "High-fidelity earbuds with planar drivers and LDAC support.",
    specs: {
      "Driver Type": "Planar",
      "Codec Support": "LDAC",
      "Battery Life": "7 hours",
      "Noise Cancellation": "Yes",
      Weight: "5.4g per earbud",
    },
    pros: ["Planar drivers", "LDAC support", "Great sound", "Good battery"],
    cons: ["Niche features", "Limited app", "Premium pricing"],
    score: {
      Design: 4.5,
      Performance: 4.7,
      "Sound Quality": 4.8,
      "Battery Life": 4.6,
      Value: 4.5,
    },
  },
  {
    id: "sony-wf-1000xm6",
    name: "Sony WF-1000XM6",
    brand: "Sony",
    category: "bluetooth-headsets",
    price: 299,
    originalPrice: 349,
    rating: 4.8,
    reviewCount: 3421,
    amazonUrl: `https://amzn.to/4tMdsbD?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["sony-wf-1000xm6"],
    description: "Industry-leading noise-canceling earbuds with premium sound quality.",
    specs: {
      "Driver Size": "8.6mm",
      "Noise Cancellation": "Best-in-class",
      "Battery Life": "8 hours",
      "Total with Case": "24 hours",
      Weight: "5.9g per earbud",
    },
    pros: ["Best noise cancellation", "Excellent sound", "Great battery", "Premium build"],
    cons: ["Very expensive", "Sony ecosystem", "Limited customization"],
    score: {
      Design: 4.8,
      Performance: 4.9,
      "Sound Quality": 4.9,
      "Battery Life": 4.7,
      Value: 4.4,
    },
  },
  {
    id: "sleep-headphones",
    name: "Sleep Headphones Headband Headphones",
    brand: "Generic",
    category: "bluetooth-headsets",
    price: 49,
    originalPrice: 99,
    rating: 4.2,
    reviewCount: 834,
    amazonUrl: `https://amzn.to/4v1MzBv?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["sleep-headphones"],
    description: "Comfortable headband headphones designed for sleeping.",
    specs: {
      "Driver Size": "6mm",
      "Battery Life": "10 hours",
      Material: "Soft fabric",
      Washable: "Yes",
      Weight: "150g",
    },
    pros: ["Very affordable", "Comfortable", "Washable", "Long battery"],
    cons: ["Basic sound", "Limited features", "Niche use"],
    score: {
      Design: 4.3,
      Performance: 4.1,
      Comfort: 4.6,
      "Battery Life": 4.5,
      Value: 4.6,
    },
  },

  // ═══════════════════════════════════════════════════════════════════════
  // WEARABLE JEWELRY (4 products)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "tangem-ring",
    name: "TANGEM Ring",
    brand: "TANGEM",
    category: "wearable-jewelry",
    price: 399,
    originalPrice: 499,
    rating: 4.5,
    reviewCount: 1245,
    amazonUrl: `https://amzn.to/43qBrlS?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["tangem-ring"],
    description: "Crypto hardware wallet ring for secure digital asset management.",
    specs: {
      Material: "Titanium",
      "Crypto Support": "Bitcoin, Ethereum",
      "Security": "Hardware wallet",
      Weight: "3g",
      Durability: "Extremely durable",
    },
    pros: ["Secure crypto storage", "Durable design", "Stylish", "Portable"],
    cons: ["Crypto-focused", "Premium pricing", "Niche market"],
    score: {
      Design: 4.6,
      Performance: 4.6,
      Security: 4.9,
      Durability: 4.8,
      Value: 4.2,
    },
  },
  {
    id: "vtech-sn5147",
    name: "VTech SN5147",
    brand: "VTech",
    category: "wearable-jewelry",
    price: 29,
    originalPrice: 59,
    rating: 4.0,
    reviewCount: 456,
    amazonUrl: `https://amzn.to/4dCyGTk?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["vtech-sn5147"],
    description: "Educational wearable jewelry for kids.",
    specs: {
      Material: "Plastic",
      "Educational Features": "Yes",
      "Battery Life": "3-5 days",
      Weight: "15g",
      "Age Range": "3+",
    },
    pros: ["Very affordable", "Educational", "Durable", "Fun design"],
    cons: ["Limited features", "Plastic build", "Basic functionality"],
    score: {
      Design: 4.1,
      Performance: 4.0,
      "Educational Value": 4.3,
      Durability: 4.1,
      Value: 4.6,
    },
  },
  {
    id: "white-pearl-band",
    name: "White Pearl Smartwatch Band",
    brand: "Generic",
    category: "wearable-jewelry",
    price: 19,
    originalPrice: 39,
    rating: 4.3,
    reviewCount: 567,
    amazonUrl: `https://amzn.to/4wLLvU7?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["white-pearl-band"],
    description: "Elegant pearl smartwatch band for fashion-forward users.",
    specs: {
      Material: "Pearl/Stainless steel",
      Compatibility: "Universal",
      Design: "Elegant",
      Weight: "20g",
      "Dress Code": "Formal/Casual",
    },
    pros: ["Elegant design", "Affordable", "Universal fit", "Stylish"],
    cons: ["Limited durability", "Fragile", "Pearl quality varies"],
    score: {
      Design: 4.6,
      Performance: 4.2,
      Style: 4.7,
      Durability: 4.1,
      Value: 4.5,
    },
  },
  {
    id: "enamel-smart-ring",
    name: "Enamel Smart Ring",
    brand: "Generic",
    category: "wearable-jewelry",
    price: 49,
    originalPrice: 99,
    rating: 4.2,
    reviewCount: 678,
    amazonUrl: `https://amzn.to/4uvtCYe?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["enamel-smart-ring"],
    description: "Stylish enamel smart ring with basic health tracking.",
    specs: {
      Material: "Enamel/Gold",
      "Health Features": "Basic",
      Weight: "2g",
      Design: "Fashionable",
      Durability: "Moderate",
    },
    pros: ["Stylish design", "Affordable", "Lightweight", "Fashion-forward"],
    cons: ["Limited features", "Fragile enamel", "Basic tracking"],
    score: {
      Design: 4.5,
      Performance: 4.1,
      Style: 4.6,
      Durability: 4.0,
      Value: 4.4,
    },
  },

  // ═══════════════════════════════════════════════════════════════════════
  // BLUETOOTH HATS & CAPS (6 products)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "aleck-snow-helmet",
    name: "Aleck Snow Series Core Wireless Bluetooth Helmet Speakers",
    brand: "Aleck",
    category: "bluetooth-hats",
    price: 79,
    originalPrice: 129,
    rating: 4.4,
    reviewCount: 1245,
    amazonUrl: `https://amzn.to/3PTfuc6?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["aleck-snow-helmet"],
    description: "Wireless Bluetooth speakers integrated into a snow helmet.",
    specs: {
      "Speaker Power": "10W",
      "Battery Life": "8 hours",
      Material: "Helmet + plastic",
      Waterproof: "Yes",
      Weight: "400g",
    },
    pros: ["Integrated speakers", "Waterproof", "Good battery", "Affordable"],
    cons: ["Limited sound quality", "Helmet-specific", "Bulky"],
    score: {
      Design: 4.3,
      Performance: 4.3,
      "Sound Quality": 4.2,
      "Battery Life": 4.5,
      Value: 4.4,
    },
  },
  {
    id: "open-type-sunhat",
    name: "Open Type Sunhat with Bluetooth Speakers",
    brand: "Generic",
    category: "bluetooth-hats",
    price: 59,
    originalPrice: 99,
    rating: 4.2,
    reviewCount: 834,
    amazonUrl: `https://amzn.to/4tRPqfk?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["open-type-sunhat"],
    description: "Lightweight sunhat with integrated Bluetooth speakers.",
    specs: {
      "Speaker Power": "5W",
      "Battery Life": "6 hours",
      Material: "Fabric + plastic",
      "UV Protection": "Yes",
      Weight: "200g",
    },
    pros: ["Lightweight", "UV protection", "Affordable", "Stylish"],
    cons: ["Limited sound", "Fragile speakers", "Basic features"],
    score: {
      Design: 4.3,
      Performance: 4.1,
      "Sound Quality": 4.0,
      "Battery Life": 4.3,
      Value: 4.4,
    },
  },
  {
    id: "custom-beanie",
    name: "Custom Beanie for Men & Women",
    brand: "Generic",
    category: "bluetooth-hats",
    price: 39,
    originalPrice: 79,
    rating: 4.1,
    reviewCount: 567,
    amazonUrl: `https://amzn.to/4tRPtI2?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["custom-beanie"],
    description: "Customizable beanie with Bluetooth speaker integration.",
    specs: {
      "Speaker Power": "3W",
      "Battery Life": "5 hours",
      Material: "Wool/Acrylic",
      Customizable: "Yes",
      Weight: "150g",
    },
    pros: ["Customizable", "Affordable", "Warm", "Lightweight"],
    cons: ["Limited sound", "Basic features", "Fragile"],
    score: {
      Design: 4.2,
      Performance: 4.0,
      "Sound Quality": 3.9,
      "Battery Life": 4.2,
      Value: 4.5,
    },
  },
  {
    id: "unisex-beanie",
    name: "Unisex Knitted Beanie",
    brand: "Generic",
    category: "bluetooth-hats",
    price: 29,
    originalPrice: 59,
    rating: 4.0,
    reviewCount: 456,
    amazonUrl: `https://amzn.to/4dqFSDh?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["unisex-beanie"],
    description: "Simple knitted beanie with basic Bluetooth speaker.",
    specs: {
      "Speaker Power": "2W",
      "Battery Life": "4 hours",
      Material: "Knit",
      "One Size": "Fits all",
      Weight: "120g",
    },
    pros: ["Very affordable", "Comfortable", "Warm", "Simple design"],
    cons: ["Very limited sound", "Short battery", "Basic features"],
    score: {
      Design: 4.1,
      Performance: 3.9,
      "Sound Quality": 3.8,
      "Battery Life": 4.0,
      Value: 4.6,
    },
  },
  {
    id: "withmoons-cap",
    name: "WITHMOONS",
    brand: "WITHMOONS",
    category: "bluetooth-hats",
    price: 49,
    originalPrice: 99,
    rating: 4.2,
    reviewCount: 678,
    amazonUrl: `https://amzn.to/4nFyxTC?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["withmoons-cap"],
    description: "Stylish cap with integrated Bluetooth speaker.",
    specs: {
      "Speaker Power": "5W",
      "Battery Life": "6 hours",
      Material: "Cotton/Polyester",
      Style: "Baseball cap",
      Weight: "180g",
    },
    pros: ["Stylish design", "Good speaker", "Affordable", "Comfortable"],
    cons: ["Limited features", "Basic sound", "Fragile"],
    score: {
      Design: 4.3,
      Performance: 4.2,
      "Sound Quality": 4.1,
      "Battery Life": 4.3,
      Value: 4.4,
    },
  },
  {
    id: "msa-hard-hat",
    name: "MSA 475395 Skullgard Cap Hard Hat",
    brand: "MSA",
    category: "bluetooth-hats",
    price: 89,
    originalPrice: 139,
    rating: 4.3,
    reviewCount: 745,
    amazonUrl: `https://amzn.to/4fCiRP4?tag=${AFFILIATE_TAG}`,
    image: PRODUCT_IMAGES["msa-hard-hat"],
    description: "Professional hard hat with Bluetooth speaker for construction sites.",
    specs: {
      "Speaker Power": "8W",
      "Battery Life": "10 hours",
      Material: "Polycarbonate",
      "Safety Rating": "ANSI Z89.1",
      Weight: "450g",
    },
    pros: ["Professional grade", "Safety certified", "Long battery", "Durable"],
    cons: ["Heavy", "Limited sound", "Niche use"],
    score: {
      Design: 4.2,
      Performance: 4.3,
      "Sound Quality": 4.2,
      "Battery Life": 4.6,
      Value: 4.3,
    },
  },
];

export const categories: Category[] = [
  {
    id: "smartwatches",
    name: "Smart Watches",
    description: "Advanced wearable technology for everyday use",
    productCount: 7,
  },
  {
    id: "fitness-trackers",
    name: "Sport Activity Trackers",
    description: "Specialized devices for fitness and sports tracking",
    productCount: 6,
  },
  {
    id: "smart-rings",
    name: "Smart Rings",
    description: "Compact health and fitness monitoring rings",
    productCount: 4,
  },
  {
    id: "smart-glasses",
    name: "Smart Glasses",
    description: "AR and smart glasses for immersive experiences",
    productCount: 6,
  },
  {
    id: "vr-headsets",
    name: "Cell Phone Virtual Reality",
    description: "VR headsets for gaming and entertainment",
    productCount: 6,
  },
  {
    id: "kids-wearables",
    name: "Wearable Tech for Kids",
    description: "Fun and educational wearables for children",
    productCount: 6,
  },
  {
    id: "pet-tech",
    name: "Tech for your Pets",
    description: "Smart devices for pet monitoring and care",
    productCount: 6,
  },
  {
    id: "bluetooth-headsets",
    name: "Cell Phone Bluetooth Headsets",
    description: "Wireless audio devices for calls and music",
    productCount: 6,
  },
  {
    id: "wearable-jewelry",
    name: "Wearable Tech Jewelry",
    description: "Stylish tech-integrated jewelry and accessories",
    productCount: 4,
  },
  {
    id: "bluetooth-hats",
    name: "Blue Tooth Capable Hats & Caps",
    description: "Hats and caps with integrated Bluetooth speakers",
    productCount: 6,
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.category === categoryId);
}

export function getTopRatedProducts(limit: number = 10): Product[] {
  return [...products].sort((a, b) => b.rating - a.rating).slice(0, limit);
}

export function getCategoryById(id: string): Category | undefined {
  return categories.find((c) => c.id === id);
}
