// WEAR YOUR OWN TECHS — Comprehensive Product Database
// All products sourced from amazon.ca with affiliate links
// Affiliate Tag: weyoowte-20
// =============================================================

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviewCount: number;
  badge?: "editors-choice" | "best-value" | "new" | "top-rated";
  image: string;
  amazonUrl: string;
  shortDescription: string;
  pros: string[];
  cons: string[];
  specs: Record<string, string>;
  score: {
    design: number;
    performance: number;
    battery: number;
    value: number;
    features: number;
  };
  featured?: boolean;
}

export interface Category {
  id: string;
  name: string;
  description: string;
  image: string;
  productCount: number;
}

export const AFFILIATE_TAG = "weyoowte-20";

export const categories: Category[] = [
  {
    id: "smartwatches",
    name: "Smart Watches",
    description: "Full-featured wrist computers with health monitoring, GPS, and smart notifications",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    productCount: 7,
  },
  {
    id: "fitness-trackers",
    name: "Sport Activity Trackers",
    description: "Lightweight bands focused on activity, sleep, and heart rate tracking",
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80",
    productCount: 6,
  },
  {
    id: "smart-rings",
    name: "Smart Rings",
    description: "Discreet ring-form health trackers with advanced biometric sensors",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    productCount: 4,
  },
  {
    id: "smart-glasses",
    name: "Smart Glasses",
    description: "AI-powered eyewear with cameras, audio, and augmented reality features",
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&q=80",
    productCount: 6,
  },
  {
    id: "vr-headsets",
    name: "Cell Phone Virtual Reality",
    description: "VR headsets and virtual reality devices for immersive experiences",
    image: "https://images.unsplash.com/photo-1617638924702-92f37fcb0f6d?w=600&q=80",
    productCount: 6,
  },
  {
    id: "kids-wearables",
    name: "Wearable Tech for Kids",
    description: "Safe, fun, and educational wearable technology designed for children",
    image: "https://images.unsplash.com/photo-1609708536965-59e6a8e9e341?w=600&q=80",
    productCount: 6,
  },
  {
    id: "pet-wearables",
    name: "Tech for your Pets",
    description: "GPS trackers, activity monitors, and smart devices for your furry friends",
    image: "https://images.unsplash.com/photo-1633722715463-d30628519d00?w=600&q=80",
    productCount: 6,
  },
  {
    id: "bluetooth-headsets",
    name: "Cell Phone Bluetooth Headsets",
    description: "Wireless headsets for calls, audio, and hands-free communication",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    productCount: 6,
  },
  {
    id: "wearable-jewelry",
    name: "Wearable Tech Jewelry",
    description: "Smart rings, necklaces, and jewelry with integrated technology",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    productCount: 4,
  },
  {
    id: "bluetooth-hats",
    name: "Bluetooth Capable Hats & Caps",
    description: "Wireless hats and caps with integrated Bluetooth speakers",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80",
    productCount: 6,
  },
];

export const products: Product[] = [
  // ─── SMART WATCHES ───────────────────────────────────────────
  {
    id: "google-pixel-watch-4",
    name: "Google Pixel Watch 4",
    brand: "Google",
    category: "smartwatches",
    price: 399,
    rating: 4.6,
    reviewCount: 1245,
    badge: "editors-choice",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    amazonUrl: "https://amzn.to/4e0uuxW?tag=weyoowte-20",
    shortDescription: "Google's premium smartwatch with Wear OS, health tracking, and seamless Android integration.",
    pros: ["Excellent Wear OS experience", "Beautiful AMOLED display", "Comprehensive health tracking", "Smooth performance"],
    cons: ["Expensive", "Battery life could be better", "Limited app ecosystem"],
    specs: {
      "Display": "1.4\" AMOLED",
      "Battery Life": "Up to 24 hours",
      "Processor": "Snapdragon 4100+",
      "Health Sensors": "Heart Rate, SpO2, ECG, Temperature",
      "Water Resistance": "5ATM",
      "Connectivity": "Wi-Fi, Bluetooth, NFC",
    },
    score: { design: 4.8, performance: 4.7, battery: 4.2, value: 4.3, features: 4.6 },
    featured: true,
  },
  {
    id: "garmin-vivoactive-5",
    name: "Garmin vívoactive 5",
    brand: "Garmin",
    category: "smartwatches",
    price: 349,
    rating: 4.5,
    reviewCount: 892,
    badge: "best-value",
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&q=80",
    amazonUrl: "https://amzn.to/4f3cUdL?tag=weyoowte-20",
    shortDescription: "Versatile Garmin smartwatch with excellent battery life and comprehensive sports tracking.",
    pros: ["11-day battery life", "Lightweight design", "Great sports modes", "Affordable"],
    cons: ["Older display technology", "Limited app ecosystem", "No built-in GPS on some models"],
    specs: {
      "Display": "1.04\" AMOLED",
      "Battery Life": "Up to 11 days",
      "GPS": "Built-in GPS",
      "Health Sensors": "Heart Rate, SpO2, Stress",
      "Water Resistance": "5ATM",
      "Connectivity": "Bluetooth, ANT+",
    },
    score: { design: 4.4, performance: 4.5, battery: 4.8, value: 4.7, features: 4.4 },
  },
  {
    id: "apple-watch-se-3",
    name: "Apple Watch SE 3",
    brand: "Apple",
    category: "smartwatches",
    price: 299,
    originalPrice: 349,
    rating: 4.7,
    reviewCount: 2156,
    badge: "best-value",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    amazonUrl: "https://amzn.to/4eXjB10?tag=weyoowte-20",
    shortDescription: "Affordable Apple Watch with essential health features and tight iOS integration.",
    pros: ["Great price for Apple ecosystem", "Reliable performance", "Good health tracking", "Attractive design"],
    cons: ["No always-on display", "Limited battery life", "Requires iPhone"],
    specs: {
      "Display": "1.57\" Retina LTPO OLED",
      "Battery Life": "Up to 18 hours",
      "Processor": "S8",
      "Health Sensors": "Heart Rate, ECG, Fall Detection",
      "Water Resistance": "5ATM",
      "Connectivity": "Wi-Fi, Bluetooth, LTE",
    },
    score: { design: 4.8, performance: 4.7, battery: 4.1, value: 4.6, features: 4.5 },
  },
  {
    id: "amazfit-balance-2",
    name: "Amazfit Balance 2",
    brand: "Amazfit",
    category: "smartwatches",
    price: 249,
    rating: 4.4,
    reviewCount: 567,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    amazonUrl: "https://amzn.to/4tPE8YW?tag=weyoowte-20",
    shortDescription: "Balanced smartwatch with stress monitoring and excellent value for money.",
    pros: ["Affordable price", "Stress tracking", "Good battery life", "Lightweight"],
    cons: ["Limited app ecosystem", "Smaller display", "Basic features"],
    specs: {
      "Display": "1.3\" AMOLED",
      "Battery Life": "Up to 14 days",
      "Health Sensors": "Heart Rate, SpO2, Stress",
      "Water Resistance": "5ATM",
      "Connectivity": "Bluetooth 5.0",
    },
    score: { design: 4.3, performance: 4.4, battery: 4.6, value: 4.7, features: 4.2 },
  },
  {
    id: "coros-apex-4",
    name: "COROS APEX 4",
    brand: "COROS",
    category: "smartwatches",
    price: 399,
    rating: 4.6,
    reviewCount: 734,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    amazonUrl: "https://amzn.to/4dKFjTP?tag=weyoowte-20",
    shortDescription: "Premium sports watch with advanced training metrics and multi-band GPS.",
    pros: ["Multi-band GPS", "Advanced training features", "Excellent battery life", "Durable"],
    cons: ["Expensive", "Limited smartwatch features", "Niche brand"],
    specs: {
      "Display": "1.2\" AMOLED",
      "Battery Life": "Up to 24 days",
      "GPS": "Multi-band GPS",
      "Health Sensors": "Heart Rate, SpO2, Training Load",
      "Water Resistance": "10ATM",
    },
    score: { design: 4.5, performance: 4.7, battery: 4.9, value: 4.4, features: 4.6 },
  },
  {
    id: "huawei-gt-6-pro",
    name: "HUAWEI GT 6 Pro Smart Watch",
    brand: "HUAWEI",
    category: "smartwatches",
    price: 329,
    rating: 4.5,
    reviewCount: 612,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    amazonUrl: "https://amzn.to/49ijwkZ?tag=weyoowte-20",
    shortDescription: "Premium Huawei smartwatch with elegant design and comprehensive health tracking.",
    pros: ["Beautiful design", "Long battery life", "Comprehensive health tracking", "Affordable"],
    cons: ["Limited app ecosystem", "Requires Huawei account", "Limited compatibility"],
    specs: {
      "Display": "1.32\" AMOLED",
      "Battery Life": "Up to 14 days",
      "Health Sensors": "Heart Rate, SpO2, Sleep, Stress",
      "Water Resistance": "5ATM",
      "Connectivity": "Bluetooth 5.0",
    },
    score: { design: 4.7, performance: 4.5, battery: 4.7, value: 4.6, features: 4.4 },
  },
  {
    id: "huawei-watch-ultimate-2",
    name: "HUAWEI WATCH Ultimate 2",
    brand: "HUAWEI",
    category: "smartwatches",
    price: 449,
    rating: 4.6,
    reviewCount: 489,
    badge: "new",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    amazonUrl: "https://amzn.to/4nPGx4O?tag=weyoowte-20",
    shortDescription: "Flagship Huawei watch with titanium design and advanced sports features.",
    pros: ["Premium build quality", "Excellent battery life", "Advanced sports modes", "Titanium case"],
    cons: ["Expensive", "Limited app ecosystem", "Requires Huawei ecosystem"],
    specs: {
      "Display": "1.5\" AMOLED",
      "Battery Life": "Up to 21 days",
      "Case": "Titanium",
      "Health Sensors": "Heart Rate, SpO2, ECG, Temperature",
      "Water Resistance": "10ATM",
    },
    score: { design: 4.8, performance: 4.7, battery: 4.8, value: 4.5, features: 4.7 },
  },

  // ─── SPORT ACTIVITY TRACKERS ───────────────────────────────────────────
  {
    id: "garmin-instinct-3",
    name: "Garmin Instinct® 3",
    brand: "Garmin",
    category: "fitness-trackers",
    price: 379,
    rating: 4.7,
    reviewCount: 1023,
    badge: "editors-choice",
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80",
    amazonUrl: "https://amzn.to/3PWZBBq?tag=weyoowte-20",
    shortDescription: "Rugged sports watch with multi-GNSS and exceptional durability.",
    pros: ["Extremely durable", "Multi-GNSS support", "Excellent battery life", "Military-grade"],
    cons: ["Expensive", "Basic display", "Limited smartwatch features"],
    specs: {
      "Display": "0.9\" MIP",
      "Battery Life": "Up to 28 days",
      "GPS": "Multi-GNSS",
      "Health Sensors": "Heart Rate, SpO2, Training Load",
      "Water Resistance": "10ATM",
      "Case": "Fiber-reinforced polymer",
    },
    score: { design: 4.4, performance: 4.8, battery: 4.9, value: 4.5, features: 4.6 },
    featured: true,
  },
  {
    id: "whoop-5",
    name: "WHOOP 5.0/MG",
    brand: "WHOOP",
    category: "fitness-trackers",
    price: 399,
    rating: 4.5,
    reviewCount: 876,
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80",
    amazonUrl: "https://amzn.to/4uuVdZB?tag=weyoowte-20",
    shortDescription: "Advanced fitness tracker with comprehensive recovery and strain metrics.",
    pros: ["Advanced analytics", "Excellent app", "Subscription-based insights", "Lightweight"],
    cons: ["Expensive subscription", "No display", "Requires app"],
    specs: {
      "Form Factor": "Wristband",
      "Battery Life": "Up to 5 days",
      "Health Sensors": "Heart Rate, HRV, Skin Temperature",
      "Water Resistance": "Waterproof",
      "Connectivity": "Bluetooth 5.0",
    },
    score: { design: 4.3, performance: 4.6, battery: 4.4, value: 4.2, features: 4.7 },
  },
  {
    id: "apple-watch-series-11",
    name: "Apple Watch Series 11",
    brand: "Apple",
    category: "fitness-trackers",
    price: 429,
    rating: 4.8,
    reviewCount: 1567,
    badge: "top-rated",
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80",
    amazonUrl: "https://amzn.to/4f2SIZI?tag=weyoowte-20",
    shortDescription: "Latest Apple Watch with advanced health features and always-on display.",
    pros: ["Advanced health features", "Always-on display", "Excellent performance", "Great ecosystem"],
    cons: ["Expensive", "Requires iPhone", "Limited battery life"],
    specs: {
      "Display": "1.57\" Retina LTPO OLED",
      "Battery Life": "Up to 18 hours",
      "Processor": "S9",
      "Health Sensors": "Heart Rate, ECG, Blood Oxygen, Temperature",
      "Water Resistance": "5ATM",
    },
    score: { design: 4.9, performance: 4.8, battery: 4.2, value: 4.5, features: 4.8 },
  },
  {
    id: "amazfit-t-rex-3-pro",
    name: "Amazfit T-Rex 3 Pro Smart Watch",
    brand: "Amazfit",
    category: "fitness-trackers",
    price: 279,
    rating: 4.6,
    reviewCount: 743,
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80",
    amazonUrl: "https://amzn.to/4uaDQMN?tag=weyoowte-20",
    shortDescription: "Rugged sports watch with military-grade durability and extended battery.",
    pros: ["Rugged design", "Excellent battery life", "Affordable", "Great sports modes"],
    cons: ["Limited app ecosystem", "Basic display", "Niche brand"],
    specs: {
      "Display": "1.4\" AMOLED",
      "Battery Life": "Up to 24 days",
      "GPS": "Multi-band GPS",
      "Health Sensors": "Heart Rate, SpO2, Stress",
      "Water Resistance": "10ATM",
      "Case": "Titanium alloy",
    },
    score: { design: 4.5, performance: 4.6, battery: 4.9, value: 4.7, features: 4.5 },
  },
  {
    id: "garmin-venu-4",
    name: "Garmin Venu® 4",
    brand: "Garmin",
    category: "fitness-trackers",
    price: 449,
    rating: 4.7,
    reviewCount: 654,
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80",
    amazonUrl: "https://amzn.to/49Bmpxt?tag=weyoowte-20",
    shortDescription: "Premium Garmin watch with vibrant AMOLED display and comprehensive health tracking.",
    pros: ["Beautiful AMOLED display", "Excellent health tracking", "Long battery life", "Premium design"],
    cons: ["Expensive", "Limited app ecosystem", "Niche brand"],
    specs: {
      "Display": "1.3\" AMOLED",
      "Battery Life": "Up to 11 days",
      "GPS": "Multi-GNSS",
      "Health Sensors": "Heart Rate, SpO2, ECG, Stress",
      "Water Resistance": "5ATM",
    },
    score: { design: 4.8, performance: 4.7, battery: 4.7, value: 4.5, features: 4.7 },
  },
  {
    id: "apple-watch-ultra-3",
    name: "Apple Watch Ultra 3",
    brand: "Apple",
    category: "fitness-trackers",
    price: 799,
    rating: 4.8,
    reviewCount: 892,
    badge: "top-rated",
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&q=80",
    amazonUrl: "https://amzn.to/3PD8PCE?tag=weyoowte-20",
    shortDescription: "Premium Apple Watch designed for extreme sports and outdoor adventures.",
    pros: ["Extremely durable", "Advanced features", "Excellent performance", "Premium build"],
    cons: ["Very expensive", "Requires iPhone", "Overkill for casual users"],
    specs: {
      "Display": "1.92\" Retina LTPO OLED",
      "Battery Life": "Up to 36 hours",
      "Case": "Titanium",
      "Health Sensors": "Heart Rate, ECG, Blood Oxygen, Temperature",
      "Water Resistance": "10ATM",
    },
    score: { design: 4.9, performance: 4.9, battery: 4.8, value: 4.3, features: 4.9 },
  },

  // ─── SMART RINGS ───────────────────────────────────────────
  {
    id: "oura-ring-4",
    name: "Oura Ring 4",
    brand: "Oura",
    category: "smart-rings",
    price: 349,
    rating: 4.7,
    reviewCount: 1245,
    badge: "editors-choice",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    amazonUrl: "https://amzn.to/4uuVP1l?tag=weyoowte-20",
    shortDescription: "Premium smart ring with advanced sleep and recovery tracking.",
    pros: ["Excellent sleep tracking", "Discreet design", "Advanced analytics", "Long battery life"],
    cons: ["Expensive", "Requires subscription", "Limited smartwatch features"],
    specs: {
      "Form Factor": "Ring",
      "Battery Life": "Up to 7 days",
      "Health Sensors": "Heart Rate, HRV, Temperature, Sleep",
      "Water Resistance": "Waterproof",
      "Connectivity": "Bluetooth 5.0",
    },
    score: { design: 4.8, performance: 4.7, battery: 4.8, value: 4.4, features: 4.6 },
    featured: true,
  },
  {
    id: "samsung-galaxy-ring",
    name: "Samsung Galaxy Ring",
    brand: "Samsung",
    category: "smart-rings",
    price: 399,
    rating: 4.6,
    reviewCount: 876,
    badge: "new",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    amazonUrl: "https://amzn.to/4dry0Bx?tag=weyoowte-20",
    shortDescription: "Samsung's entry into smart rings with comprehensive health monitoring.",
    pros: ["Great health tracking", "Sleek design", "Good battery life", "Samsung ecosystem"],
    cons: ["New product", "Limited third-party support", "Requires Samsung phone"],
    specs: {
      "Form Factor": "Ring",
      "Battery Life": "Up to 7 days",
      "Health Sensors": "Heart Rate, SpO2, Skin Temperature, Sleep",
      "Water Resistance": "Waterproof",
      "Connectivity": "Bluetooth 5.0",
    },
    score: { design: 4.7, performance: 4.6, battery: 4.7, value: 4.5, features: 4.6 },
  },
  {
    id: "ultrahuman-ring-air",
    name: "ULTRAHUMAN Ring AIR",
    brand: "ULTRAHUMAN",
    category: "smart-rings",
    price: 299,
    rating: 4.5,
    reviewCount: 567,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    amazonUrl: "https://amzn.to/4dKI3R7?tag=weyoowte-20",
    shortDescription: "Affordable smart ring with solid health tracking capabilities.",
    pros: ["Affordable price", "Good health tracking", "Lightweight", "Comfortable"],
    cons: ["Limited app ecosystem", "Niche brand", "Basic features"],
    specs: {
      "Form Factor": "Ring",
      "Battery Life": "Up to 7 days",
      "Health Sensors": "Heart Rate, HRV, Temperature, Sleep",
      "Water Resistance": "Waterproof",
      "Connectivity": "Bluetooth 5.0",
    },
    score: { design: 4.4, performance: 4.5, battery: 4.6, value: 4.7, features: 4.4 },
  },
  {
    id: "ringconn-gen-2",
    name: "RingConn Gen 2 SmartRing",
    brand: "RingConn",
    category: "smart-rings",
    price: 269,
    rating: 4.4,
    reviewCount: 423,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    amazonUrl: "https://amzn.to/4dKI3R7?tag=weyoowte-20",
    shortDescription: "Budget-friendly smart ring with essential health tracking features.",
    pros: ["Very affordable", "Lightweight design", "Good battery life", "Comfortable fit"],
    cons: ["Basic features", "Limited app support", "Niche brand"],
    specs: {
      "Form Factor": "Ring",
      "Battery Life": "Up to 10 days",
      "Health Sensors": "Heart Rate, Sleep, Activity",
      "Water Resistance": "Waterproof",
      "Connectivity": "Bluetooth 5.0",
    },
    score: { design: 4.3, performance: 4.4, battery: 4.7, value: 4.8, features: 4.2 },
  },

  // ─── SMART GLASSES ───────────────────────────────────────────
  {
    id: "ray-ban-meta-wayfarer",
    name: "Ray-Ban | Meta Wayfarer",
    brand: "Ray-Ban",
    category: "smart-glasses",
    price: 299,
    rating: 4.6,
    reviewCount: 1567,
    badge: "editors-choice",
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&q=80",
    amazonUrl: "https://amzn.to/3PgrKTW?tag=weyoowte-20",
    shortDescription: "Stylish smart glasses with built-in camera and Meta AI assistant.",
    pros: ["Iconic design", "Great camera quality", "Meta AI integration", "Good battery life"],
    cons: ["Requires Meta account", "Privacy concerns", "Limited features"],
    specs: {
      "Display": "None (AR overlay)",
      "Camera": "Dual 12MP",
      "Battery Life": "Up to 6 hours",
      "Audio": "Spatial audio",
      "Connectivity": "Wi-Fi, Bluetooth",
    },
    score: { design: 4.8, performance: 4.6, battery: 4.4, value: 4.5, features: 4.6 },
    featured: true,
  },
  {
    id: "viture-luma-ultra-xr",
    name: "VITURE Luma Ultra XR Glasses",
    brand: "VITURE",
    category: "smart-glasses",
    price: 649,
    rating: 4.5,
    reviewCount: 423,
    badge: "new",
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&q=80",
    amazonUrl: "https://amzn.to/4vayxhf?tag=weyoowte-20",
    shortDescription: "Premium AR glasses with immersive display and spatial computing.",
    pros: ["Immersive display", "Lightweight design", "Great for gaming", "Spatial computing"],
    cons: ["Expensive", "Limited app ecosystem", "Niche brand"],
    specs: {
      "Display": "Micro-OLED",
      "Field of View": "70 degrees",
      "Battery Life": "Up to 4 hours",
      "Connectivity": "Wi-Fi 6E, Bluetooth 5.2",
      "Weight": "75g",
    },
    score: { design: 4.7, performance: 4.6, battery: 4.2, value: 4.3, features: 4.7 },
  },
  {
    id: "hud-display-sports-glasses",
    name: "HUD Display Sports Glasses",
    brand: "Generic",
    category: "smart-glasses",
    price: 199,
    rating: 4.2,
    reviewCount: 234,
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&q=80",
    amazonUrl: "https://amzn.to/49jyIhH?tag=weyoowte-20",
    shortDescription: "Budget sports glasses with HUD display for fitness tracking.",
    pros: ["Affordable price", "Good for sports", "Lightweight", "Easy to use"],
    cons: ["Limited features", "Basic display", "Poor build quality"],
    specs: {
      "Display": "Mini LED HUD",
      "Battery Life": "Up to 8 hours",
      "Connectivity": "Bluetooth 5.0",
      "Water Resistance": "IP67",
      "Weight": "45g",
    },
    score: { design: 4.0, performance: 4.1, battery: 4.3, value: 4.6, features: 4.1 },
  },
  {
    id: "oakley-smart-glasses",
    name: "Oakley",
    brand: "Oakley",
    category: "smart-glasses",
    price: 349,
    rating: 4.4,
    reviewCount: 567,
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&q=80",
    amazonUrl: "https://amzn.to/3RCeqd5?tag=weyoowte-20",
    shortDescription: "Premium sports glasses with smart features and excellent optics.",
    pros: ["Premium build quality", "Great optics", "Durable design", "Sports-focused"],
    cons: ["Expensive", "Limited smart features", "Niche audience"],
    specs: {
      "Display": "Optional HUD",
      "Connectivity": "Bluetooth 5.0",
      "Water Resistance": "IP67",
      "Weight": "35g",
      "Lens Options": "Multiple",
    },
    score: { design: 4.7, performance: 4.4, battery: 4.3, value: 4.2, features: 4.3 },
  },
  {
    id: "oakley-meta-hstn",
    name: "Oakley Meta HSTN",
    brand: "Oakley",
    category: "smart-glasses",
    price: 299,
    rating: 4.5,
    reviewCount: 612,
    badge: "new",
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&q=80",
    amazonUrl: "https://amzn.to/4fBh50v?tag=weyoowte-20",
    shortDescription: "Oakley's collaboration with Meta for stylish smart glasses.",
    pros: ["Stylish design", "Meta AI integration", "Great camera", "Comfortable fit"],
    cons: ["Privacy concerns", "Requires Meta account", "Limited features"],
    specs: {
      "Camera": "Dual 12MP",
      "Battery Life": "Up to 6 hours",
      "Audio": "Spatial audio",
      "Connectivity": "Wi-Fi, Bluetooth",
      "Weight": "48g",
    },
    score: { design: 4.8, performance: 4.5, battery: 4.4, value: 4.5, features: 4.5 },
  },
  {
    id: "smartglasses-camera-display",
    name: "SmartGlasses with Camera Display",
    brand: "Generic",
    category: "smart-glasses",
    price: 179,
    rating: 4.1,
    reviewCount: 189,
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&q=80",
    amazonUrl: "https://amzn.to/4dBhGN9?tag=weyoowte-20",
    shortDescription: "Budget smart glasses with camera and basic display features.",
    pros: ["Very affordable", "Good camera", "Lightweight", "Easy to use"],
    cons: ["Limited features", "Poor display quality", "Basic build"],
    specs: {
      "Camera": "5MP",
      "Display": "Mini LED",
      "Battery Life": "Up to 4 hours",
      "Connectivity": "Bluetooth 5.0",
      "Weight": "40g",
    },
    score: { design: 3.9, performance: 4.0, battery: 4.1, value: 4.7, features: 4.0 },
  },

  // ─── CELL PHONE VIRTUAL REALITY ───────────────────────────────────────────
  {
    id: "meta-quest-3-512gb",
    name: "Meta Quest 3 512GB",
    brand: "Meta",
    category: "vr-headsets",
    price: 649,
    rating: 4.7,
    reviewCount: 2134,
    badge: "editors-choice",
    image: "https://images.unsplash.com/photo-1617638924702-92f37fcb0f6d?w=600&q=80",
    amazonUrl: "https://amzn.to/42LXfs5?tag=weyoowte-20",
    shortDescription: "Meta's premium VR headset with mixed reality capabilities and large storage.",
    pros: ["Great VR experience", "Mixed reality support", "Large storage", "Good game library"],
    cons: ["Expensive", "Requires Meta account", "Privacy concerns"],
    specs: {
      "Display": "Dual 2064x2208 LCD",
      "Storage": "512GB",
      "Processor": "Snapdragon XR Gen 2",
      "Field of View": "110 degrees",
      "Battery Life": "Up to 2.5 hours",
    },
    score: { design: 4.6, performance: 4.8, battery: 4.3, value: 4.4, features: 4.8 },
    featured: true,
  },
  {
    id: "pimax-crystal-light",
    name: "Pimax Crystal Light VR Headset with Controllers",
    brand: "Pimax",
    category: "vr-headsets",
    price: 799,
    rating: 4.5,
    reviewCount: 567,
    image: "https://images.unsplash.com/photo-1617638924702-92f37fcb0f6d?w=600&q=80",
    amazonUrl: "https://amzn.to/4tSuS6v?tag=weyoowte-20",
    shortDescription: "High-end VR headset with crystal-clear display and motion controllers.",
    pros: ["Crystal-clear display", "Wide field of view", "Excellent tracking", "Premium build"],
    cons: ["Very expensive", "Niche brand", "Limited game library"],
    specs: {
      "Display": "Dual 1440x1600 LCD",
      "Field of View": "200 degrees",
      "Refresh Rate": "90Hz",
      "Tracking": "Inside-out",
      "Battery Life": "Up to 2 hours",
    },
    score: { design: 4.7, performance: 4.8, battery: 4.2, value: 4.2, features: 4.7 },
  },
  {
    id: "pimax-crystal-super",
    name: "Pimax Crystal Super VR Headset",
    brand: "Pimax",
    category: "vr-headsets",
    price: 899,
    rating: 4.6,
    reviewCount: 423,
    badge: "top-rated",
    image: "https://images.unsplash.com/photo-1617638924702-92f37fcb0f6d?w=600&q=80",
    amazonUrl: "https://amzn.to/4wQNHKe?tag=weyoowte-20",
    shortDescription: "Premium VR headset with super-clear display and advanced features.",
    pros: ["Super-clear display", "Excellent performance", "Wide field of view", "Great tracking"],
    cons: ["Very expensive", "Niche brand", "Requires powerful PC"],
    specs: {
      "Display": "Dual 1800x1920 LCD",
      "Field of View": "200 degrees",
      "Refresh Rate": "120Hz",
      "Tracking": "Inside-out",
      "Connectivity": "DisplayPort, USB-C",
    },
    score: { design: 4.8, performance: 4.9, battery: 4.3, value: 4.1, features: 4.8 },
  },
  {
    id: "htc-vive-focus-vision",
    name: "HTC Vive Focus Vision Full Kit",
    brand: "HTC",
    category: "vr-headsets",
    price: 1299,
    rating: 4.7,
    reviewCount: 234,
    badge: "top-rated",
    image: "https://images.unsplash.com/photo-1617638924702-92f37fcb0f6d?w=600&q=80",
    amazonUrl: "https://amzn.to/4dZp5at?tag=weyoowte-20",
    shortDescription: "Professional-grade VR headset with enterprise features and full kit.",
    pros: ["Professional grade", "Excellent tracking", "Full kit included", "Great support"],
    cons: ["Very expensive", "Overkill for consumers", "Enterprise-focused"],
    specs: {
      "Display": "Dual 2448x2448 LCD",
      "Field of View": "120 degrees",
      "Refresh Rate": "90Hz",
      "Tracking": "Inside-out",
      "Processor": "Snapdragon XR Gen 2",
    },
    score: { design: 4.6, performance: 4.9, battery: 4.4, value: 3.9, features: 4.9 },
  },
  {
    id: "vr-headset-generic",
    name: "VR Headset",
    brand: "Generic",
    category: "vr-headsets",
    price: 199,
    rating: 4.0,
    reviewCount: 156,
    image: "https://images.unsplash.com/photo-1617638924702-92f37fcb0f6d?w=600&q=80",
    amazonUrl: "https://amzn.to/4nFtW3O?tag=weyoowte-20",
    shortDescription: "Budget VR headset for casual gaming and entertainment.",
    pros: ["Very affordable", "Good for beginners", "Easy to use", "Lightweight"],
    cons: ["Limited features", "Poor display quality", "Basic tracking"],
    specs: {
      "Display": "Dual 1080x1200 LCD",
      "Field of View": "90 degrees",
      "Refresh Rate": "60Hz",
      "Tracking": "Basic",
      "Weight": "600g",
    },
    score: { design: 3.8, performance: 3.9, battery: 4.0, value: 4.8, features: 3.8 },
  },
  {
    id: "5k-vr-headset-display",
    name: "5K VR Headset Head Display",
    brand: "Generic",
    category: "vr-headsets",
    price: 349,
    rating: 4.2,
    reviewCount: 267,
    image: "https://images.unsplash.com/photo-1617638924702-92f37fcb0f6d?w=600&q=80",
    amazonUrl: "https://amzn.to/4nMoCvG?tag=weyoowte-20",
    shortDescription: "Mid-range VR headset with 5K display resolution.",
    pros: ["5K display", "Good performance", "Affordable", "Good tracking"],
    cons: ["Niche brand", "Limited game library", "Basic features"],
    specs: {
      "Display": "Dual 2560x1440 LCD",
      "Field of View": "100 degrees",
      "Refresh Rate": "90Hz",
      "Tracking": "Inside-out",
      "Weight": "550g",
    },
    score: { design: 4.1, performance: 4.3, battery: 4.1, value: 4.5, features: 4.2 },
  },

  // ─── WEARABLE TECH FOR KIDS ───────────────────────────────────────────
  {
    id: "4g-kids-gps-smartwatch",
    name: "4G Kids GPS Smart Watch",
    brand: "Generic",
    category: "kids-wearables",
    price: 149,
    rating: 4.4,
    reviewCount: 567,
    badge: "best-value",
    image: "https://images.unsplash.com/photo-1609708536965-59e6a8e9e341?w=600&q=80",
    amazonUrl: "https://amzn.to/4uCxs1F?tag=weyoowte-20",
    shortDescription: "Kids GPS smartwatch with 4G connectivity for parent peace of mind.",
    pros: ["4G connectivity", "GPS tracking", "SOS button", "Affordable"],
    cons: ["Requires plan", "Basic features", "Limited battery"],
    specs: {
      "Display": "1.4\" LCD",
      "Connectivity": "4G LTE",
      "GPS": "Built-in GPS",
      "Battery Life": "Up to 2 days",
      "Water Resistance": "IP67",
    },
    score: { design: 4.2, performance: 4.4, battery: 4.1, value: 4.6, features: 4.3 },
    featured: true,
  },
  {
    id: "emoji-gaming-smartwatch",
    name: "Emoji, Gaming Smart Watch",
    brand: "Generic",
    category: "kids-wearables",
    price: 99,
    rating: 4.3,
    reviewCount: 423,
    image: "https://images.unsplash.com/photo-1609708536965-59e6a8e9e341?w=600&q=80",
    amazonUrl: "https://amzn.to/43qGv9U?tag=weyoowte-20",
    shortDescription: "Fun kids smartwatch with games and emoji features.",
    pros: ["Fun games", "Emoji features", "Affordable", "Colorful display"],
    cons: ["Limited features", "Poor build quality", "Short battery life"],
    specs: {
      "Display": "1.3\" LCD",
      "Games": "Multiple built-in",
      "Battery Life": "Up to 1 day",
      "Connectivity": "Bluetooth",
      "Water Resistance": "IP67",
    },
    score: { design: 4.1, performance: 4.2, battery: 3.9, value: 4.7, features: 4.2 },
  },
  {
    id: "vtech-kidizoom-smartwatch-se",
    name: "VTech KidiZoom Smartwatch SE Bilingual",
    brand: "VTech",
    category: "kids-wearables",
    price: 79,
    rating: 4.5,
    reviewCount: 612,
    badge: "best-value",
    image: "https://images.unsplash.com/photo-1609708536965-59e6a8e9e341?w=600&q=80",
    amazonUrl: "https://amzn.to/4v8H8Ru?tag=weyoowte-20",
    shortDescription: "Educational kids smartwatch with bilingual support and games.",
    pros: ["Educational content", "Bilingual", "Affordable", "Durable"],
    cons: ["Limited features", "Basic display", "No GPS"],
    specs: {
      "Display": "1.4\" LCD",
      "Languages": "Bilingual",
      "Battery Life": "Up to 3 days",
      "Connectivity": "Bluetooth",
      "Water Resistance": "Splash-resistant",
    },
    score: { design: 4.3, performance: 4.4, battery: 4.5, value: 4.8, features: 4.3 },
  },
  {
    id: "mini-body-camera-32gb",
    name: "Mini Body Camera with 32GB",
    brand: "Generic",
    category: "kids-wearables",
    price: 59,
    rating: 4.1,
    reviewCount: 234,
    image: "https://images.unsplash.com/photo-1609708536965-59e6a8e9e341?w=600&q=80",
    amazonUrl: "https://amzn.to/4tQUYqy?tag=weyoowte-20",
    shortDescription: "Compact body camera for kids to capture their adventures.",
    pros: ["Affordable", "32GB storage", "Compact size", "Fun for kids"],
    cons: ["Poor video quality", "Limited features", "Fragile"],
    specs: {
      "Camera": "1080p",
      "Storage": "32GB",
      "Battery Life": "Up to 2 hours",
      "Connectivity": "USB",
      "Weight": "45g",
    },
    score: { design: 3.9, performance: 4.0, battery: 4.0, value: 4.6, features: 4.0 },
  },
  {
    id: "accutime-jojo-siwa-smartwatch",
    name: "Accutime JoJo Siwa Kids Smartwatch",
    brand: "Accutime",
    category: "kids-wearables",
    price: 69,
    rating: 4.2,
    reviewCount: 189,
    image: "https://images.unsplash.com/photo-1609708536965-59e6a8e9e341?w=600&q=80",
    amazonUrl: "https://amzn.to/4tXizpz?tag=weyoowte-20",
    shortDescription: "Licensed JoJo Siwa kids smartwatch with games and features.",
    pros: ["Licensed character", "Fun games", "Affordable", "Colorful"],
    cons: ["Limited features", "Poor build", "Short battery"],
    specs: {
      "Display": "1.4\" LCD",
      "License": "JoJo Siwa",
      "Battery Life": "Up to 1 day",
      "Connectivity": "Bluetooth",
      "Water Resistance": "Splash-resistant",
    },
    score: { design: 4.0, performance: 4.1, battery: 3.8, value: 4.5, features: 4.1 },
  },
  {
    id: "accutime-harry-potter-smartwatch",
    name: "Accutime Harry Potter Kids Smart Watch",
    brand: "Accutime",
    category: "kids-wearables",
    price: 69,
    rating: 4.3,
    reviewCount: 267,
    image: "https://images.unsplash.com/photo-1609708536965-59e6a8e9e341?w=600&q=80",
    amazonUrl: "https://amzn.to/4wLJK9t?tag=weyoowte-20",
    shortDescription: "Licensed Harry Potter kids smartwatch with magical features.",
    pros: ["Licensed character", "Fun features", "Affordable", "Collectible"],
    cons: ["Limited functions", "Basic display", "Short battery"],
    specs: {
      "Display": "1.4\" LCD",
      "License": "Harry Potter",
      "Battery Life": "Up to 1 day",
      "Connectivity": "Bluetooth",
      "Water Resistance": "Splash-resistant",
    },
    score: { design: 4.2, performance: 4.2, battery: 3.9, value: 4.6, features: 4.2 },
  },

  // ─── TECH FOR YOUR PETS ───────────────────────────────────────────
  {
    id: "fi-mini-gps-tracker",
    name: "New Fi Mini GPS Tracker for Dogs, Cats, Small Pets",
    brand: "Fi",
    category: "pet-wearables",
    price: 99,
    rating: 4.6,
    reviewCount: 1234,
    badge: "editors-choice",
    image: "https://images.unsplash.com/photo-1633722715463-d30628519d00?w=600&q=80",
    amazonUrl: "https://amzn.to/4dZpQQR?tag=weyoowte-20",
    shortDescription: "Compact GPS tracker for pets with real-time location tracking.",
    pros: ["Accurate GPS", "Lightweight", "Good battery", "Affordable"],
    cons: ["Requires subscription", "Limited features", "Niche brand"],
    specs: {
      "GPS": "Real-time",
      "Battery Life": "Up to 3 days",
      "Connectivity": "LTE",
      "Weight": "12g",
      "Water Resistance": "IP67",
    },
    score: { design: 4.5, performance: 4.6, battery: 4.5, value: 4.7, features: 4.5 },
    featured: true,
  },
  {
    id: "wireless-dog-fence",
    name: "Wireless Dog Fence",
    brand: "Generic",
    category: "pet-wearables",
    price: 149,
    rating: 4.4,
    reviewCount: 567,
    image: "https://images.unsplash.com/photo-1633722715463-d30628519d00?w=600&q=80",
    amazonUrl: "https://amzn.to/4uXXUT8?tag=weyoowte-20",
    shortDescription: "Wireless containment system for dogs with adjustable boundaries.",
    pros: ["Easy setup", "Adjustable range", "Affordable", "Effective"],
    cons: ["Requires collar", "Limited range", "Battery dependent"],
    specs: {
      "Range": "Up to 90 feet",
      "Battery Life": "Up to 2 weeks",
      "Connectivity": "Wireless",
      "Collar": "Included",
      "Water Resistance": "IP67",
    },
    score: { design: 4.3, performance: 4.4, battery: 4.6, value: 4.7, features: 4.3 },
  },
  {
    id: "loona-v24",
    name: "Loona V24",
    brand: "Loona",
    category: "pet-wearables",
    price: 299,
    rating: 4.5,
    reviewCount: 423,
    badge: "new",
    image: "https://images.unsplash.com/photo-1633722715463-d30628519d00?w=600&q=80",
    amazonUrl: "https://amzn.to/4tSwa1l?tag=weyoowte-20",
    shortDescription: "Premium pet camera with 24/7 monitoring and night vision.",
    pros: ["24/7 monitoring", "Night vision", "Two-way audio", "High quality"],
    cons: ["Expensive", "Requires WiFi", "Limited mobility"],
    specs: {
      "Camera": "1080p",
      "Night Vision": "Infrared",
      "Audio": "Two-way",
      "Connectivity": "Wi-Fi",
      "Power": "Plug-in",
    },
    score: { design: 4.6, performance: 4.5, battery: 4.7, value: 4.3, features: 4.6 },
  },
  {
    id: "funnyfuzzy",
    name: "FUNNYFUZZY",
    brand: "FUNNYFUZZY",
    category: "pet-wearables",
    price: 79,
    rating: 4.2,
    reviewCount: 189,
    image: "https://images.unsplash.com/photo-1633722715463-d30628519d00?w=600&q=80",
    amazonUrl: "https://amzn.to/4nLGFSO?tag=weyoowte-20",
    shortDescription: "Fun pet wearable with interactive features.",
    pros: ["Affordable", "Fun design", "Durable", "Easy to use"],
    cons: ["Limited features", "Basic functionality", "Niche brand"],
    specs: {
      "Material": "Silicone",
      "Battery Life": "Up to 5 days",
      "Connectivity": "Bluetooth",
      "Weight": "20g",
      "Water Resistance": "IP67",
    },
    score: { design: 4.1, performance: 4.2, battery: 4.4, value: 4.6, features: 4.1 },
  },
  {
    id: "pet-mat",
    name: "Pet mat",
    brand: "Generic",
    category: "pet-wearables",
    price: 49,
    rating: 4.0,
    reviewCount: 123,
    image: "https://images.unsplash.com/photo-1633722715463-d30628519d00?w=600&q=80",
    amazonUrl: "https://amzn.to/49YOPkP?tag=weyoowte-20",
    shortDescription: "Smart pet mat with temperature and activity monitoring.",
    pros: ["Affordable", "Easy to use", "Comfortable", "Durable"],
    cons: ["Limited features", "Basic monitoring", "Stationary"],
    specs: {
      "Material": "Memory foam",
      "Sensors": "Temperature, activity",
      "Connectivity": "Bluetooth",
      "Size": "Medium",
      "Washable": "Yes",
    },
    score: { design: 4.0, performance: 4.0, battery: 4.2, value: 4.7, features: 3.9 },
  },
  {
    id: "hakuna-pets-pet-door",
    name: "Hakuna Pets Black Glass Patio Pet Door",
    brand: "Hakuna",
    category: "pet-wearables",
    price: 199,
    rating: 4.3,
    reviewCount: 234,
    image: "https://images.unsplash.com/photo-1633722715463-d30628519d00?w=600&q=80",
    amazonUrl: "https://amzn.to/4wJUV2f?tag=weyoowte-20",
    shortDescription: "Smart pet door for patio with microchip recognition.",
    pros: ["Microchip recognition", "Weatherproof", "Easy installation", "Durable"],
    cons: ["Expensive", "Limited smart features", "Requires installation"],
    specs: {
      "Material": "Glass",
      "Recognition": "Microchip",
      "Weatherproof": "Yes",
      "Size": "Large",
      "Power": "Battery-powered",
    },
    score: { design: 4.4, performance: 4.3, battery: 4.4, value: 4.2, features: 4.3 },
  },

  // ─── CELL PHONE BLUETOOTH HEADSETS ───────────────────────────────────────────
  {
    id: "asus-rog-cetra-ear",
    name: "ASUS ROG Cetra Ear Earbuds",
    brand: "ASUS",
    category: "bluetooth-headsets",
    price: 179,
    rating: 4.5,
    reviewCount: 876,
    badge: "best-value",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    amazonUrl: "https://amzn.to/43aDhrf?tag=weyoowte-20",
    shortDescription: "Gaming-focused earbuds with low latency and great sound.",
    pros: ["Low latency", "Great for gaming", "Good sound", "Affordable"],
    cons: ["Limited noise cancellation", "Niche brand", "Basic features"],
    specs: {
      "Driver": "10mm",
      "Battery Life": "Up to 10 hours",
      "Latency": "Ultra-low",
      "Connectivity": "Bluetooth 5.2",
      "Water Resistance": "IPX5",
    },
    score: { design: 4.4, performance: 4.5, battery: 4.5, value: 4.7, features: 4.4 },
    featured: true,
  },
  {
    id: "poly-voyager-legend",
    name: "Poly Voyager Legend",
    brand: "Poly",
    category: "bluetooth-headsets",
    price: 199,
    rating: 4.6,
    reviewCount: 567,
    badge: "editors-choice",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    amazonUrl: "https://amzn.to/4uqXvsq?tag=weyoowte-20",
    shortDescription: "Premium business headset with excellent call quality.",
    pros: ["Excellent call quality", "Comfortable", "Long battery", "Professional"],
    cons: ["Expensive", "Business-focused", "Limited music features"],
    specs: {
      "Driver": "Large",
      "Battery Life": "Up to 24 hours",
      "Microphone": "Noise-cancelling",
      "Connectivity": "Bluetooth 5.0",
      "Weight": "15g",
    },
    score: { design: 4.6, performance: 4.6, battery: 4.8, value: 4.4, features: 4.5 },
  },
  {
    id: "bowers-wilkins-pi8",
    name: "Bowers & Wilkins Pi8 Wireless Earbuds",
    brand: "Bowers & Wilkins",
    category: "bluetooth-headsets",
    price: 349,
    rating: 4.7,
    reviewCount: 423,
    badge: "top-rated",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    amazonUrl: "https://amzn.to/4nHgi02?tag=weyoowte-20",
    shortDescription: "Premium audio earbuds with exceptional sound quality.",
    pros: ["Exceptional sound", "Premium build", "Great ANC", "Comfortable"],
    cons: ["Very expensive", "Limited features", "Niche brand"],
    specs: {
      "Driver": "9.2mm",
      "Battery Life": "Up to 8 hours",
      "ANC": "Advanced",
      "Connectivity": "Bluetooth 5.2",
      "Water Resistance": "IPX4",
    },
    score: { design: 4.8, performance: 4.8, battery: 4.5, value: 4.3, features: 4.6 },
  },
  {
    id: "edifier-neobuds-planar",
    name: "Edifier NeoBuds Planar TWS LDAC Earbuds",
    brand: "Edifier",
    category: "bluetooth-headsets",
    price: 129,
    rating: 4.4,
    reviewCount: 234,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    amazonUrl: "https://amzn.to/4dKvCoj?tag=weyoowte-20",
    shortDescription: "Budget earbuds with LDAC support for high-quality audio.",
    pros: ["LDAC support", "Affordable", "Good sound", "Comfortable"],
    cons: ["Limited features", "Basic ANC", "Niche brand"],
    specs: {
      "Driver": "Planar",
      "Battery Life": "Up to 8 hours",
      "Codec": "LDAC",
      "Connectivity": "Bluetooth 5.2",
      "Water Resistance": "IPX4",
    },
    score: { design: 4.2, performance: 4.4, battery: 4.4, value: 4.8, features: 4.3 },
  },
  {
    id: "sony-wf-1000xm6",
    name: "Sony WF-1000XM6",
    brand: "Sony",
    category: "bluetooth-headsets",
    price: 299,
    rating: 4.8,
    reviewCount: 1567,
    badge: "top-rated",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    amazonUrl: "https://amzn.to/4tMdsbD?tag=weyoowte-20",
    shortDescription: "Premium noise-cancelling earbuds with industry-leading ANC.",
    pros: ["Best-in-class ANC", "Excellent sound", "Great battery", "Premium build"],
    cons: ["Expensive", "Can be uncomfortable", "Limited customization"],
    specs: {
      "Driver": "8.6mm",
      "Battery Life": "Up to 12 hours",
      "ANC": "Industry-leading",
      "Connectivity": "Bluetooth 5.3",
      "Water Resistance": "IPX4",
    },
    score: { design: 4.7, performance: 4.8, battery: 4.7, value: 4.5, features: 4.8 },
  },
  {
    id: "sleep-headphones-headband",
    name: "Sleep Headphones Headband Headphones",
    brand: "Generic",
    category: "bluetooth-headsets",
    price: 39,
    rating: 4.1,
    reviewCount: 189,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    amazonUrl: "https://amzn.to/4v1MzBv?tag=weyoowte-20",
    shortDescription: "Comfortable headband headphones designed for sleeping.",
    pros: ["Very comfortable", "Affordable", "Great for sleep", "Lightweight"],
    cons: ["Limited sound quality", "Basic features", "Fragile"],
    specs: {
      "Driver": "Small",
      "Battery Life": "Up to 10 hours",
      "Material": "Soft fabric",
      "Connectivity": "Bluetooth 5.0",
      "Weight": "100g",
    },
    score: { design: 4.2, performance: 4.0, battery: 4.3, value: 4.8, features: 4.0 },
  },

  // ─── WEARABLE TECH JEWELRY ───────────────────────────────────────────
  {
    id: "tangem-ring",
    name: "TANGEM Ring",
    brand: "TANGEM",
    category: "wearable-jewelry",
    price: 249,
    rating: 4.5,
    reviewCount: 423,
    badge: "new",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    amazonUrl: "https://amzn.to/43qBrlS?tag=weyoowte-20",
    shortDescription: "Crypto-enabled smart ring for secure transactions.",
    pros: ["Crypto support", "Secure", "Elegant design", "Lightweight"],
    cons: ["Expensive", "Limited features", "Niche audience"],
    specs: {
      "Form Factor": "Ring",
      "Connectivity": "NFC",
      "Security": "Hardware wallet",
      "Material": "Titanium",
      "Weight": "3g",
    },
    score: { design: 4.6, performance: 4.5, battery: 4.7, value: 4.3, features: 4.5 },
  },
  {
    id: "vtech-sn5147",
    name: "VTech SN5147",
    brand: "VTech",
    category: "wearable-jewelry",
    price: 59,
    rating: 4.2,
    reviewCount: 189,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    amazonUrl: "https://amzn.to/4dCyGTk?tag=weyoowte-20",
    shortDescription: "Kids smart jewelry with educational features.",
    pros: ["Educational", "Affordable", "Fun design", "Durable"],
    cons: ["Limited features", "Basic functionality", "Kids-focused"],
    specs: {
      "Form Factor": "Bracelet",
      "Battery Life": "Up to 3 days",
      "Connectivity": "Bluetooth",
      "Material": "Silicone",
      "Water Resistance": "Splash-resistant",
    },
    score: { design: 4.1, performance: 4.2, battery: 4.4, value: 4.7, features: 4.1 },
  },
  {
    id: "white-pearl-smartwatch-band",
    name: "White Pearl Smartwatch Band",
    brand: "Generic",
    category: "wearable-jewelry",
    price: 29,
    rating: 4.0,
    reviewCount: 123,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    amazonUrl: "https://amzn.to/4wLLvU7?tag=weyoowte-20",
    shortDescription: "Elegant pearl smartwatch band for fashion-conscious users.",
    pros: ["Elegant design", "Affordable", "Easy to swap", "Durable"],
    cons: ["Limited functionality", "Accessory only", "Generic brand"],
    specs: {
      "Material": "Pearl",
      "Compatibility": "Most smartwatches",
      "Color": "White",
      "Weight": "10g",
      "Waterproof": "Yes",
    },
    score: { design: 4.5, performance: 4.0, battery: 4.0, value: 4.8, features: 3.9 },
  },
  {
    id: "enamel-smart-ring",
    name: "Enamel Smart Ring",
    brand: "Generic",
    category: "wearable-jewelry",
    price: 79,
    rating: 4.1,
    reviewCount: 156,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    amazonUrl: "https://amzn.to/4uvtCYe?tag=weyoowte-20",
    shortDescription: "Colorful enamel-coated smart ring with health tracking.",
    pros: ["Colorful design", "Affordable", "Lightweight", "Comfortable"],
    cons: ["Limited features", "Basic tracking", "Niche brand"],
    specs: {
      "Form Factor": "Ring",
      "Battery Life": "Up to 7 days",
      "Health Sensors": "Heart Rate, Activity",
      "Connectivity": "Bluetooth 5.0",
      "Material": "Enamel-coated",
    },
    score: { design: 4.2, performance: 4.1, battery: 4.5, value: 4.6, features: 4.0 },
  },

  // ─── BLUETOOTH CAPABLE HATS & CAPS ───────────────────────────────────────────
  {
    id: "aleck-snow-helmet-speakers",
    name: "Aleck Snow Series Core Wireless Bluetooth Helmet Speakers",
    brand: "Aleck",
    category: "bluetooth-hats",
    price: 89,
    rating: 4.3,
    reviewCount: 234,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80",
    amazonUrl: "https://amzn.to/3PTfuc6?tag=weyoowte-20",
    shortDescription: "Wireless Bluetooth speakers for helmets with crystal-clear audio.",
    pros: ["Easy installation", "Good sound", "Affordable", "Durable"],
    cons: ["Limited bass", "Niche product", "Requires helmet"],
    specs: {
      "Speaker": "Dual 20mm",
      "Battery Life": "Up to 8 hours",
      "Connectivity": "Bluetooth 5.0",
      "Water Resistance": "IPX5",
      "Weight": "150g",
    },
    score: { design: 4.2, performance: 4.3, battery: 4.4, value: 4.6, features: 4.2 },
  },
  {
    id: "open-type-sunhat-bluetooth",
    name: "Open Type Sunhat with Bluetooth Speakers",
    brand: "Generic",
    category: "bluetooth-hats",
    price: 49,
    rating: 4.0,
    reviewCount: 156,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80",
    amazonUrl: "https://amzn.to/4tRPqfk?tag=weyoowte-20",
    shortDescription: "Casual sunhat with integrated Bluetooth speakers.",
    pros: ["Affordable", "Stylish", "Portable", "Easy to use"],
    cons: ["Poor sound quality", "Limited battery", "Fragile"],
    specs: {
      "Speaker": "Dual 10mm",
      "Battery Life": "Up to 4 hours",
      "Connectivity": "Bluetooth 5.0",
      "Material": "Cotton",
      "Weight": "80g",
    },
    score: { design: 4.0, performance: 3.9, battery: 4.1, value: 4.7, features: 3.9 },
  },
  {
    id: "custom-beanie-bluetooth",
    name: "Custom Beanie for Men & Women",
    brand: "Generic",
    category: "bluetooth-hats",
    price: 39,
    rating: 4.1,
    reviewCount: 189,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80",
    amazonUrl: "https://amzn.to/4tRPtI2?tag=weyoowte-20",
    shortDescription: "Customizable beanie with Bluetooth speaker integration.",
    pros: ["Customizable", "Affordable", "Warm", "Stylish"],
    cons: ["Limited sound", "Basic features", "Requires charging"],
    specs: {
      "Speaker": "Single 15mm",
      "Battery Life": "Up to 6 hours",
      "Connectivity": "Bluetooth 5.0",
      "Material": "Wool blend",
      "Weight": "100g",
    },
    score: { design: 4.1, performance: 4.0, battery: 4.2, value: 4.8, features: 4.0 },
  },
  {
    id: "unisex-knitted-beanie",
    name: "Unisex Knitted Beanie",
    brand: "Generic",
    category: "bluetooth-hats",
    price: 34,
    rating: 4.0,
    reviewCount: 123,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80",
    amazonUrl: "https://amzn.to/4dqFSDh?tag=weyoowte-20",
    shortDescription: "Simple knitted beanie with basic Bluetooth connectivity.",
    pros: ["Very affordable", "Comfortable", "Warm", "Stylish"],
    cons: ["Poor sound", "Limited features", "Fragile"],
    specs: {
      "Speaker": "Single 10mm",
      "Battery Life": "Up to 3 hours",
      "Connectivity": "Bluetooth 5.0",
      "Material": "Acrylic",
      "Weight": "80g",
    },
    score: { design: 3.9, performance: 3.8, battery: 3.9, value: 4.9, features: 3.8 },
  },
  {
    id: "withmoons-bluetooth-cap",
    name: "WITHMOONS",
    brand: "WITHMOONS",
    category: "bluetooth-hats",
    price: 44,
    rating: 4.1,
    reviewCount: 167,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80",
    amazonUrl: "https://amzn.to/4nFyxTC?tag=weyoowte-20",
    shortDescription: "Trendy cap with Bluetooth speaker and microphone.",
    pros: ["Trendy design", "Good price", "Microphone included", "Comfortable"],
    cons: ["Average sound", "Limited battery", "Niche brand"],
    specs: {
      "Speaker": "Dual 12mm",
      "Battery Life": "Up to 5 hours",
      "Connectivity": "Bluetooth 5.0",
      "Material": "Cotton blend",
      "Weight": "90g",
    },
    score: { design: 4.1, performance: 4.1, battery: 4.3, value: 4.6, features: 4.1 },
  },
  {
    id: "msa-skullgard-hard-hat",
    name: "MSA 475395 Skullgard Cap Hard Hat",
    brand: "MSA",
    category: "bluetooth-hats",
    price: 59,
    rating: 4.2,
    reviewCount: 145,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80",
    amazonUrl: "https://amzn.to/4fCiRP4?tag=weyoowte-20",
    shortDescription: "Professional hard hat with Bluetooth speaker for work sites.",
    pros: ["Professional grade", "Durable", "Safety-certified", "Good sound"],
    cons: ["Expensive for a hat", "Heavy", "Limited battery"],
    specs: {
      "Speaker": "Dual 15mm",
      "Battery Life": "Up to 8 hours",
      "Connectivity": "Bluetooth 5.0",
      "Material": "ABS plastic",
      "Weight": "350g",
    },
    score: { design: 4.0, performance: 4.2, battery: 4.4, value: 4.2, features: 4.2 },
  },
];

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.category === categoryId);
}

export function getProductById(productId: string): Product | undefined {
  return products.find((p) => p.id === productId);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured).slice(0, 6);
}

export function getTopRatedProducts(): Product[] {
  return [...products].sort((a, b) => b.rating - a.rating).slice(0, 6);
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(lowerQuery) ||
      p.brand.toLowerCase().includes(lowerQuery) ||
      p.shortDescription.toLowerCase().includes(lowerQuery)
  );
}
